const puppeteer = require('puppeteer-core');
const path = require('path');
const CHROME = 'C:/Program Files/Google/Chrome/Application/chrome.exe';
const URL = 'file:///' + path.resolve(process.argv[2]).split(path.sep).join('/');
let fails = 0, passes = 0;
function ok(cond, msg) { if (cond) { passes++; console.log('  ok   ' + msg); } else { fails++; console.log('  FAIL ' + msg); } }
const sleep = ms => new Promise(r => setTimeout(r, ms));
(async () => {
  const browser = await puppeteer.launch({ executablePath: CHROME, headless: true, args: ['--mute-audio', '--disable-speech-api', '--disable-gpu'] });
  const page = await browser.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push('pageerror: ' + e.message));
  page.on('console', m => { if (m.type() === 'error' && !/fonts\.g|net::ERR/.test(m.text())) errors.push('console: ' + m.text()); });
  await page.setViewport({ width: 1200, height: 900 });
  await page.goto(URL, { waitUntil: 'load' });
  await sleep(600);
  const text = (sel) => page.$eval(sel, el => el.textContent.trim());
  const visible = (sel) => page.$eval(sel, el => !el.hidden && el.offsetParent !== null);
  const attr = (sel, a) => page.$eval(sel, (el, a) => el.getAttribute(a), a);
  const count = async (sel) => (await page.$$(sel)).length;
  const world = () => page.evaluate(() => document.documentElement.getAttribute('data-world'));
  const T = () => page.evaluate(() => ({ screen: __spelling.G.screen, word: __spelling.G.cur && __spelling.G.cur.w, phase: __spelling.G.phase, pearls: __spelling.S.worlds[__spelling.world()].pearls, streak: __spelling.G.streak, grade: __spelling.S.grade, kid: __spelling.S.kid, level: __spelling.levelFor(__spelling.S.worlds[__spelling.world()].pearls) }));
  const typeAnswer = async (w) => { await page.focus('#spellInput'); await page.type('#spellInput', w); await page.keyboard.press('Enter'); await sleep(450); };
  const away = async () => { await page.mouse.move(4, 400); await sleep(250); };
  const tap = async (sel) => { await page.$eval(sel, el => el.scrollIntoView({ block: 'center' })); await sleep(200); const r = await page.$eval(sel, el => { const b = el.getBoundingClientRect(); return { x: b.left + b.width / 2, y: b.top + b.height / 2 }; }); await page.$eval(sel, el => el.click()); await sleep(100); };

  console.log('1. Player screen');
  ok(await visible('#scr-profiles'), 'player screen shown first');
  ok(await count('.profile-card') === 2, 'two player cards');
  ok((await text('.profile-card[data-id="charlie"] .pc-sub')).startsWith('4th grade'), 'Charlie defaults to 4th grade');
  ok((await text('.profile-card[data-id="riley"] .pc-sub')).startsWith('3rd grade'), 'Riley defaults to 3rd grade');
  ok(await world() === 'lagoon', 'default look is lagoon before choosing');

  console.log('2. Hover previews on player tiles');
  await page.hover('.profile-card[data-id="charlie"]'); await sleep(250);
  ok(await world() === 'candy', 'hovering Charlie previews the candy world');
  ok(await text('#brand') === 'Spelling Sweetshop', 'brand switches on hover');
  await away();
  ok(await world() === 'lagoon', 'leaving the tile restores the lagoon');
  await page.hover('.profile-card[data-id="riley"]'); await sleep(250);
  ok(await world() === 'lagoon', 'hovering Riley shows the lagoon');
  await away();

  console.log('3. Pick Charlie');
  await page.click('.profile-card[data-id="charlie"]'); await sleep(500);
  ok(await visible('#scr-home'), 'home shown');
  ok(await world() === 'candy', 'Charlie is in the candy world');
  ok(await text('#playerName') === 'Charlie', 'playing as Charlie');
  ok(await attr('.seg-btn.on', 'data-g') === '4', '4th grade selected');
  ok(await text('#axoNameHome') === 'Gummy Bear', 'default candy character');
  ok(await text('#gradeLabel') === '4th grade', 'mastered line says 4th grade');
  await page.hover('#gradeSeg .seg-btn[data-g="3"]'); await sleep(300);
  ok(await world() === 'lagoon', 'hovering 3rd grade previews the lagoon');
  ok(await text('#axoNameHome') === 'Axolotl', 'preview swaps the character too');
  await away();
  ok(await world() === 'candy' && await text('#axoNameHome') === 'Gummy Bear', 'leaving restores candy and character');

  console.log('4. Character picker');
  await page.click('.char-chip[data-char="cupcake"]'); await sleep(300);
  ok(await text('#axoNameHome') === 'Cupcake', 'cupcake chosen');
  ok(await attr('.char-chip.on', 'data-char') === 'cupcake', 'chip highlighted');
  ok(await count('.char-chip') === 6, 'six candy characters');

  console.log('5. Spell It round: correct, wrong + lock-in, hint, retry, summary');
  await page.evaluate(() => { __spelling.S.roundLen = '5'; __spelling.save(); });
  await page.click('.mode-btn[data-mode="spell"]'); await sleep(700);
  ok(await visible('#scr-play'), 'play screen shown');
  let t = await T(); ok(!!t.word, 'a word is loaded: ' + t.word);
  ok((await text('#roundLabel')).indexOf('4th grade') >= 0, 'round label names the grade');
  ok(await count('#dots .dot') === 5, 'five progress dots');
  const before = t.pearls;
  await typeAnswer(t.word);
  t = await T();
  ok(t.phase === 'done', 'correct answer accepted');
  ok(t.pearls === before + 10, 'earned 10 (' + before + ' -> ' + t.pearls + ')');
  ok(t.streak === 1, 'streak is 1');
  ok(await count('#resultBox .tile.ok') === t.word.length, 'a green tile for every letter');
  ok(await count('#dots .dot.first') === 1, 'dot marked green');
  await sleep(2200);
  t = await T(); ok(t.phase === 'answer' && !!t.word, 'auto-advanced to: ' + t.word);
  const w2 = t.word;
  await typeAnswer('zzq');
  t = await T();
  ok(t.phase === 'lockin', 'wrong answer enters lock-in');
  ok(await visible('#lockinBox') && (await text('#lockinBox')).indexOf(w2) >= 0, 'lock-in box shows the correct word');
  ok(await count('#resultBox .tile.bad') > 0, 'wrong letters marked');
  ok(await count('#resultBox .tile.miss') > 0, 'missing letters marked');
  ok(t.streak === 0 && await count('#dots .dot.miss') === 1, 'streak reset and dot marked red');
  await typeAnswer(w2);
  t = await T(); ok(t.phase === 'done' && t.pearls === before + 12, 'lock-in retype accepted for +2 (' + t.pearls + ')');
  await sleep(2200);
  t = await T(); const w3 = t.word;
  await page.click('#hintBtn'); await sleep(250);
  ok(await visible('#hintStrip') && (await text('#hintStrip .h.show')) === w3[0], 'hint reveals the first letter');
  await typeAnswer(w3);
  t = await T(); ok(t.pearls === before + 17, 'hinted answer worth 5 (' + t.pearls + ')');
  const beforeRetry = t.pearls;
  for (let i = 0; i < 14; i++) { await sleep(1500); t = await T(); if (t.screen !== 'scr-play') break; if (t.phase !== 'answer') continue; await typeAnswer(t.word); }
  await sleep(2800);
  t = await T();
  ok(t.screen === 'scr-summary', 'round ends on the summary screen');
  ok(await count('#dots .dot') === 6, 'missed word was retried at the end');
  ok(await page.evaluate(() => __spelling.G.queue[5].status === 'retry'), 'retry dot marked as a fix');
  ok((await text('#sumStats')).indexOf('of 5') >= 0, 'summary counts the 5 words');
  ok(await visible('#missedWrap') && (await text('#missedList')).indexOf(w2) >= 0, 'missed word listed');
  ok(t.level >= 1, 'reached level 1 (' + t.pearls + ' sprinkles)');
  ok(await text('#lbLevel') === 'Level ' + t.level, 'level bar updated');
  await page.click('#practiceMissed'); await sleep(600);
  t = await T(); ok(t.word === w2 && t.screen === 'scr-play', 'practice round starts with the missed word');
  await typeAnswer(w2); await sleep(2800);
  t = await T(); ok(t.screen === 'scr-summary', 'practice round ends');

  console.log('6. Levels, scenery, outfits');
  ok(await count('#scene [data-lv="1"].on') > 0, 'level 1 scenery visible');
  ok(await count('#scene [data-lv="10"].on') === 0, 'level 10 scenery hidden');
  await page.click('#sumHome'); await sleep(400);
  const unlocked = await count('.level-card:not(.locked)');
  ok(unlocked === t.level + 1, 'unlocked level cards: ' + unlocked);
  ok(await count('.level-card') === t.level + 2, 'only earned levels plus one Surprise card are shown');
  ok((await text('.level-card.mystery .lc-name')) === 'Surprise!' && (await text('.level-card.mystery .lc-lv')) === 'Level ' + (t.level + 1), 'next level is a surprise card');
  ok((await text('#levelGrid')).indexOf('Cupcake Hat') < 0 && (await text('#levelGrid')).indexOf('Rock Candy') < 0, 'future outfits are not named');
  ok(/^Level \d+ at \d+ /.test(await text('#lbNext')), 'level bar does not name the next outfit');
  ok(await count('#axoHome .acc.on') > 0, 'outfit piece worn');
  await page.click('.level-card[data-lv="0"]'); await sleep(250);
  ok(await count('#axoHome .acc.on') === 0, 'Start look removes the outfit');
  await page.click('.level-card[data-lv="1"]'); await sleep(250);
  ok(await count('#axoHome .acc.on') > 0, 'level 1 look restored');

  console.log('7. Tile Time');
  await page.click('.mode-btn[data-mode="tiles"]'); await sleep(700);
  t = await T(); ok(await visible('#tileArea') && await count('#tiles .tile.pick') === t.word.length, 'tiles laid out for: ' + t.word);
  const p0 = t.pearls;
  for (const ch of t.word) { const h = await page.evaluateHandle(ch => Array.from(document.querySelectorAll('#tiles .tile.pick:not(.used)')).find(b => b.textContent === ch), ch); await h.asElement().click(); await sleep(90); }
  await sleep(800); t = await T();
  ok(t.phase === 'done' && t.pearls === p0 + 10, 'tiles answer accepted (+10)');
  await page.click('#quitBtn'); await sleep(300);
  ok(await visible('#scr-home'), 'Home button leaves the round');

  console.log('8. Word list');
  await page.click('.mode-btn[data-mode="list"]'); await sleep(400);
  ok(await count('#wordList .word-row') === 50, '50 words in the 4th grade list');
  ok(await page.$eval('#chipCrossed', el => el.hidden), 'crossed-off chip hidden for 4th grade');
  ok(await count('#wordList .word-row[data-w="December"]') === 1, 'December listed with its capital');
  await page.click('#wordList .word-row[data-w="December"]'); await sleep(250);
  ok((await text('#wordDetail')).indexOf('twelfth') >= 0, 'word detail shows the meaning');
  await page.click('#wordsHome'); await sleep(300);

  console.log('9. December accepts lowercase');
  await page.evaluate(() => { const w = __spelling.WORDS4.find(x => x.w === 'December'); __spelling.startRound('spell', [w]); });
  await sleep(500); await typeAnswer('december');
  t = await T(); ok(t.phase === 'done', 'lowercase december accepted');
  await page.evaluate(() => document.getElementById('quitBtn').click()); await sleep(300);
  await page.evaluate(() => { const w = __spelling.WORDS4.find(x => x.w === 'kelp'); __spelling.startRound('spell', [w]); });
  await sleep(500); await typeAnswer('KeLP');
  t = await T(); ok(t.phase === 'done', 'mixed-case KeLP accepted');
  ok(await page.$eval('#spellInput', el => getComputedStyle(el).textTransform === 'none'), 'spelling box keeps what she types');
  await page.evaluate(() => document.getElementById('quitBtn').click()); await sleep(300);
  await page.evaluate(() => { const w = __spelling.WORDS4.find(x => x.w === 'December'); __spelling.startRound('spell', [w]); });
  await sleep(500); await typeAnswer('DECEMBAR');
  ok((await T()).phase === 'lockin' && await count('#resultBox .tile.ok') === 7, 'diff ignores case: 7 letters match in DECEMBAR');
  await page.evaluate(() => document.getElementById('quitBtn').click()); await sleep(300);

  console.log('10. Switching players and persistence');
  const charliePearls = (await T()).pearls;
  await page.click('#switchBtn'); await sleep(350);
  ok(await visible('#scr-profiles'), 'switch shows the player screen');
  ok((await text('.profile-card[data-id="charlie"] .pc-sub')).indexOf('level ' + t.level) >= 0, 'Charlie card shows her level');
  await page.click('.profile-card[data-id="riley"]'); await sleep(500);
  ok(await world() === 'lagoon' && await text('#playerName') === 'Riley', 'Riley lands in the lagoon');
  ok((await T()).pearls === 0, 'Riley starts at 0 pearls');
  ok(await text('#axoNameHome') === 'Axolotl', 'Riley default character');
  ok(await count('.char-chip') === 6 && await count('.char-chip[data-char="penguin"]') === 1, 'six lagoon characters');
  await page.click('.mode-btn[data-mode="list"]'); await sleep(350);
  ok(await count('#wordList .word-row') === 50 && !(await page.$eval('#chipCrossed', el => el.hidden)), '3rd grade list with the crossed-off chip');
  await page.click('#chipCrossed'); await sleep(250);
  ok(await count('#wordList .word-row') === 17, '17 crossed-off words');
  await page.click('#wordsHome'); await sleep(250);
  await page.click('#gradeSeg .seg-btn[data-g="4"]'); await away();
  ok(await world() === 'candy' && (await T()).grade === '4', 'Riley can switch to 4th grade');
  await page.click('#gradeSeg .seg-btn[data-g="3"]'); await away();
  await page.click('#switchBtn'); await sleep(300); await page.click('.profile-card[data-id="charlie"]'); await sleep(500);
  ok((await T()).pearls === charliePearls && await world() === 'candy', 'Charlie progress intact after switching');
  await page.reload({ waitUntil: 'load' }); await sleep(700);
  ok(await visible('#scr-profiles'), 'reload shows the player screen');
  await page.click('.profile-card[data-id="charlie"]'); await sleep(500);
  ok((await T()).pearls === charliePearls, 'Charlie progress survives a reload');
  ok(await text('#axoNameHome') === 'Cupcake', 'character choice survives a reload');

  console.log('10b. Saves are safe before a player is picked');
  const keepPearls = (await T()).pearls;
  await page.evaluate(() => { __spelling.G.cur = null; }); await page.reload({ waitUntil: 'load' }); await sleep(600);
  await page.click('#soundBtn'); await sleep(150); await page.click('#soundBtn'); await sleep(150);
  await page.click('.profile-card[data-id="charlie"]'); await sleep(500);
  ok((await T()).pearls === keepPearls, 'sound button on the player screen does not wipe the last save');
  await page.click('.mode-btn[data-mode="list"]'); await sleep(300); await page.click('#wordList .word-row'); await sleep(200);
  await page.click('#wordsHome'); await sleep(200); await page.click('#switchBtn'); await sleep(300);
  await page.click('.profile-card[data-id="riley"]'); await sleep(400); await page.click('.mode-btn[data-mode="list"]'); await sleep(300);
  ok((await text('#wordDetail')).indexOf('Tap a word') >= 0 && await count('#wordList .word-row.on') === 0, 'word detail does not carry over to the other player');
  await page.click('#wordsHome'); await sleep(200); await page.click('#switchBtn'); await sleep(300); await page.click('.profile-card[data-id="charlie"]'); await sleep(400);
  await page.evaluate(() => { const w = __spelling.WORDS4.find(x => x.w === 'kelp'); __spelling.startRound('tiles', [w]); }); await sleep(400);
  await page.evaluate(() => { const L = __spelling.G.tileLetters, want = 'kelp'.split(''), used = []; want.forEach(ch => { const i = L.findIndex((c, j) => c === ch && used.indexOf(j) < 0); used.push(i); document.querySelector('#tiles .tile.pick[data-i="' + i + '"]').click(); }); document.querySelector('#slots .tile.slot[data-i="3"]').click(); });
  await sleep(600);
  ok((await T()).phase === 'answer', 'removing a tile right after filling the row cancels the auto-check');
  await page.evaluate(() => document.getElementById('quitBtn').click()); await sleep(300);

  console.log('11. Sound toggle and reset');
  await page.click('#soundBtn'); await sleep(100);
  ok(await page.$eval('#soundBtn', el => el.classList.contains('off')), 'sound off');
  await page.click('#soundBtn'); await sleep(100);
  await page.click('#resetBtn'); await sleep(150); ok(await visible('#resetConfirm'), 'reset asks first');
  await page.click('#resetNo'); await sleep(150); ok(!(await visible('#resetConfirm')), 'Keep them cancels');
  await page.click('#resetBtn'); await sleep(100); await page.click('#resetYes'); await sleep(400);
  ok((await T()).pearls === 0 && await text('#lbLevel') === 'Level 0', 'reset clears progress');
  ok(await text('#axoNameHome') === 'Cupcake' && await world() === 'candy', 'reset keeps character and grade');

  console.log('12. Phone layout');
  await page.setViewport({ width: 390, height: 844, isMobile: true, hasTouch: true }); await sleep(500);
  const fits = () => page.evaluate(() => { const m = document.getElementById('main'); return document.documentElement.scrollWidth <= window.innerWidth + 1 && m.scrollWidth <= m.clientWidth + 1; });
  ok(await fits(), 'home fits at 390px wide');
  await tap('.mode-btn[data-mode="spell"]'); await sleep(600);
  ok(await fits(), 'play screen fits');
  ok(await page.$eval('#checkBtn', el => el.getBoundingClientRect().height >= 44), 'Check button is tap-sized');
  ok(await page.$eval('#spellInput', el => el.getBoundingClientRect().width > 250), 'spelling box is wide');
  await tap('#quitBtn'); await sleep(250);
  await tap('.mode-btn[data-mode="list"]'); await sleep(350);
  ok(await fits(), 'word list fits');
  await tap('#wordsHome'); await sleep(250);
  await tap('#switchBtn'); await sleep(300);
  ok(await fits(), 'player screen fits');
  console.log('12b. Keyboard-height view');
  await tap('.profile-card[data-id="charlie"]'); await sleep(500);
  await page.setViewport({ width: 390, height: 430, isMobile: true, hasTouch: true }); await sleep(500);
  await tap('.mode-btn[data-mode="spell"]'); await sleep(800);
  const within = (sel) => page.$eval(sel, el => { const r = el.getBoundingClientRect(); return r.height > 0 && r.top >= -1 && r.bottom <= window.innerHeight + 1; });
  ok(await page.evaluate(() => document.getElementById('app').getBoundingClientRect().height <= window.innerHeight + 1), 'app fits the visible height');
  ok(await within('#spellInput'), 'spelling box visible in a keyboard-sized view');
  ok(await within('#checkBtn'), 'Check button visible in a keyboard-sized view');
  ok(await page.$eval('.levelbar', el => el.offsetParent === null), 'level bar hidden during play on phones');
  await typeAnswer('zzq'); await sleep(700);
  ok(await within('#resultBox'), 'feedback visible after a miss in a keyboard-sized view');
  ok(await within('#spellInput'), 'spelling box still reachable for the lock-in retype');
  t = await T(); await typeAnswer(t.word); await sleep(600);
  ok((await T()).phase === 'done' && await page.$eval('#spellInput', el => el.readOnly && document.activeElement === el), 'input stays focused (keyboard stays open) after an answer');
  await tap('#quitBtn'); await sleep(300);

  console.log('12c. Every word in both lists, both modes');
  await page.setViewport({ width: 1200, height: 900 }); await sleep(300);
  const sweep = await page.evaluate(() => {
    const H = __spelling, bad = [], G = () => H.G, click = () => document.getElementById('checkBtn').click();
    const order = (word) => { const used = [], L = G().tileLetters; return word.toLowerCase().split('').map(ch => { for (let i = 0; i < L.length; i++) { if (L[i] === ch && used.indexOf(i) < 0) { used.push(i); return i; } } return -1; }); };
    for (const w of H.WORDS3.concat(H.WORDS4)) {
      H.startRound('spell', [w]); document.getElementById('spellInput').value = w.w.toUpperCase(); click();
      if (G().phase !== 'done') bad.push('spell upper: ' + w.w);
      H.startRound('spell', [w]); document.getElementById('spellInput').value = ' ' + w.w.toLowerCase() + ' '; click();
      if (G().phase !== 'done') bad.push('spell lower: ' + w.w);
      H.startRound('tiles', [w]);
      if (G().tileLetters.join('') === w.w.toLowerCase() && w.w.length > 2) bad.push('tiles not scrambled: ' + w.w);
      if (G().tileLetters.some(c => c !== c.toLowerCase())) bad.push('tile has a capital: ' + w.w);
      let o = order(w.w); if (o.indexOf(-1) >= 0) { bad.push('tiles missing letters: ' + w.w); continue; }
      G().tileSel = o; click(); if (G().phase !== 'done') bad.push('tiles correct: ' + w.w);
      H.startRound('tiles', [w]); o = order(w.w); const rev = o.slice().reverse();
      if (rev.map(i => G().tileLetters[i]).join('') !== w.w.toLowerCase()) { G().tileSel = rev; click(); if (G().phase !== 'lockin') bad.push('tiles wrong -> lockin: ' + w.w); o = order(w.w); G().tileSel = o; click(); if (G().phase !== 'done') bad.push('tiles lock-in retype: ' + w.w); }
      const re = new RegExp(w.w, 'ig'); if (!re.test(w.s)) bad.push('sentence lacks the word: ' + w.w);
      const pre = w.w.toLowerCase().slice(0, Math.min(5, w.w.length));
      if (w.d.toLowerCase().indexOf(pre) >= 0) bad.push('meaning gives it away: ' + w.w);
      if (w.s.replace(new RegExp(w.w, 'ig'), '____').toLowerCase().indexOf(pre) >= 0) bad.push('blanked sentence gives it away: ' + w.w);
    }
    return bad;
  });
  ok(sweep.length === 0, 'all 100 words pass upper/lower typing, tiles, and tile lock-in' + (sweep.length ? ': ' + sweep.slice(0, 8).join(' | ') : ''));
  await page.evaluate(() => { const b = document.getElementById('quitBtn'); b.click(); }); await sleep(400);
  await page.evaluate(() => { const w = __spelling.WORDS4.find(x => x.w === 'December'); __spelling.startRound('tiles', [w]); }); await sleep(400);
  await page.click('#hintBtn'); await sleep(200);
  ok(await count('#tiles .tile.pick.glow') === 1 && (await text('#tiles .tile.pick.glow')) === 'd', 'December hint glows the lowercase d tile');
  await page.evaluate(() => document.getElementById('quitBtn').click()); await sleep(300);
  console.log('13. Errors');
  ok(errors.length === 0, 'no page errors' + (errors.length ? ': ' + errors.slice(0, 3).join(' | ') : ''));
  await browser.close();
  console.log('\n' + passes + ' passed, ' + fails + ' failed');
  process.exit(fails ? 1 : 0);
})().catch(e => { console.error('TEST CRASH', e); process.exit(2); });
