const puppeteer = require('puppeteer-core');
const path = require('path');
const CHROME = 'C:/Program Files/Google/Chrome/Application/chrome.exe';
const URL = 'file:///' + path.resolve(process.argv[2]).split(path.sep).join('/');
let fails = 0, passes = 0;
function ok(cond, msg) { if (cond) { passes++; console.log('  ok   ' + msg); } else { fails++; console.log('  FAIL ' + msg); } }
const sleep = ms => new Promise(r => setTimeout(r, ms));
(async () => {
  const browser = await puppeteer.launch({ executablePath: CHROME, headless: true, args: ['--mute-audio', '--disable-speech-api', '--disable-gpu'] });
  const page = await browser.newPage();
  const cloud = require('./mockcloud').create(); await cloud.attach(page);
  const errors = [];
  page.on('pageerror', e => errors.push('pageerror: ' + e.message));
  page.on('console', m => { if (m.type() === 'error' && !/fonts\.g|net::ERR/.test(m.text())) errors.push('console: ' + m.text()); });
  await page.setViewport({ width: 1200, height: 900 });
  await page.goto(URL, { waitUntil: 'load' });
  await sleep(300);
  const waitSync = async (pg) => { for (let i = 0; i < 80; i++) { if (await pg.evaluate(() => !window.__spelling || __spelling.net.idle())) return true; await sleep(100); } return false; };
  const _reload = page.reload.bind(page); page.reload = async (o) => { await waitSync(page); return _reload(o); };
  /* the progress of the character a save is playing, the way the game finds it */
  const CK = { lagoon: 'charLagoon', candy: 'charCandy', canopy: 'charCanopy', ocean: 'charOcean', bows: 'charBows', boba: 'charBoba' }, CD = { lagoon: 'axolotl', candy: 'bear', canopy: 'sloth', ocean: 'jellyfish', bows: 'bow', boba: 'milktea' };
  const recOf = (st, make) => { const w = (st.look && CK[st.look]) ? st.look : (st.theme || (st.grade === '4' ? 'candy' : 'lagoon')), k = w + ':' + (st[CK[w]] || CD[w]);
    if (!st.chars) st.chars = {}; if (!st.chars[k]) { if (!make) return { pearls: 0 }; st.chars[k] = { pearls: 0, wearLevel: null }; } return st.chars[k]; };
  const online = async (id) => { await sleep(700); await waitSync(page); return cloud.store[id] && cloud.store[id].state; };
  cloud.store.charlie = { rev: 1, state: { restoredId: 'r20260927' } };
  await page.reload({ waitUntil: 'load' }); await sleep(600);
  const text = (sel) => page.$eval(sel, el => el.textContent.trim());
  const visible = (sel) => page.$eval(sel, el => !el.hidden && el.offsetParent !== null);
  const attr = (sel, a) => page.$eval(sel, (el, a) => el.getAttribute(a), a);
  const count = async (sel) => (await page.$$(sel)).length;
  const world = () => page.evaluate(() => document.documentElement.getAttribute('data-world'));
  const T = () => page.evaluate(() => ({ screen: __spelling.G.screen, word: __spelling.G.cur && __spelling.G.cur.w, phase: __spelling.G.phase, pearls: __spelling.SW().pearls, streak: __spelling.G.streak, grade: __spelling.S.grade, kid: __spelling.S.kid, level: __spelling.levelFor(__spelling.SW().pearls) }));
  const typeAnswer = async (w) => { await page.focus('#spellInput'); await page.type('#spellInput', w); await page.keyboard.press('Enter'); await sleep(450); };
  const away = async () => { await page.mouse.move(4, 400); await sleep(250); };
  const tap = async (sel) => { await page.$eval(sel, el => el.scrollIntoView({ block: 'center' })); await sleep(200); const r = await page.$eval(sel, el => { const b = el.getBoundingClientRect(); return { x: b.left + b.width / 2, y: b.top + b.height / 2 }; }); await page.$eval(sel, el => el.click()); await sleep(100); };

  console.log('1. Player screen');
  ok(await visible('#scr-profiles'), 'player screen shown first');
  ok(await count('.profile-card') === 6, 'six player cards');
  ok(await text('.profile-card[data-id="vera"] .pc-sub') === 'Level 0', 'player cards show only the level');
  ok(await world() === 'lagoon', 'default look is lagoon before choosing');

  console.log('2. Hover previews on player tiles');
  await page.hover('.profile-card[data-id="charlie"]'); await sleep(250);
  ok(await world() === 'candy', 'hovering Charlie previews the candy world');
  ok(await text('#brand') === 'Spelling Sweetshop', 'brand switches on hover');
  await away();
  ok(await world() === 'lagoon', 'leaving the tile restores the lagoon');
  await page.hover('.profile-card[data-id="riley"]'); await sleep(250);
  ok(await world() === 'lagoon', 'hovering Riley shows the lagoon');
  await away();

  console.log('3. Pick Charlie');
  await page.click('.profile-card[data-id="charlie"]'); await sleep(500);
  ok(await visible('#scr-home'), 'home shown');
  ok(await world() === 'candy', 'Charlie is in the candy world');
  ok(await text('#playerName') === 'Charlie', 'playing as Charlie');
  ok(await attr('.seg-btn.on', 'data-g') === '4', '4th grade selected');
  ok(await text('#axoNameHome') === 'Gummy Bear', 'default candy character');
  ok(await text('#gradeLabel') === '4th grade', 'mastered line says 4th grade');
  ok(await text('.home-badge') === '4th grade words' && await attr('.home-badge', 'data-g') === '4', 'the home badge says 4th grade words');
  await page.hover('#gradeSeg .seg-btn[data-g="3"]'); await sleep(300);
  ok(await world() === 'candy', 'hovering 3rd grade keeps Charlie in the candy world');
  ok(await text('#axoNameHome') === 'Gummy Bear', 'and keeps her character');
  const lv0 = await text('#lbLevel');
  await page.click('#gradeSeg .seg-btn[data-g="3"]'); await sleep(300);
  ok(await world() === 'candy' && await text('#lbLevel') === lv0 && await text('#gradeLabel') === '3rd grade', 'the 3rd grade list keeps her world and level, only the words change');
  ok(await text('.home-badge') === '3rd grade words' && await attr('.home-badge', 'data-g') === '3', 'the home badge says 3rd grade words');
  await page.evaluate(() => { __spelling.startRound('spell'); }); await sleep(300);
  ok(await visible('.play-badge') && await text('.play-badge') === '3rd grade words', 'the play screen shows 3rd grade words');
  await page.evaluate(() => document.getElementById('quitBtn').click()); await sleep(200);
  await page.click('#gradeSeg .seg-btn[data-g="4"]'); await sleep(300);
  await away();
  ok(await world() === 'candy' && await text('#axoNameHome') === 'Gummy Bear', 'leaving restores candy and character');

  console.log('4. Character picker');
  await page.click('.char-chip[data-char="cupcake"]'); await sleep(300);
  ok(await text('#axoNameHome') === 'Cupcake', 'cupcake chosen');
  ok(await attr('.char-chip.on', 'data-char') === 'cupcake', 'chip highlighted');
  ok(await count('.char-chip') === 6, 'six candy characters');

  console.log('5. Spell It round: correct, wrong + lock-in, hint, retry, summary');
  await page.evaluate(() => { __spelling.S.roundLen = '5'; __spelling.save(); });
  await page.click('.mode-btn[data-mode="spell"]'); await sleep(700);
  ok(await visible('#scr-play'), 'play screen shown');
  let t = await T(); ok(!!t.word, 'a word is loaded: ' + t.word);
  ok((await text('#roundLabel')).indexOf('4th grade') >= 0, 'round label names the grade');
  ok(await count('#dots .dot') === 5, 'five progress dots');
  const before = t.pearls;
  await typeAnswer(t.word);
  t = await T();
  ok(t.phase === 'done', 'correct answer accepted');
  ok(t.pearls === before + 10, 'earned 10 (' + before + ' -> ' + t.pearls + ')');
  ok(t.streak === 1, 'streak is 1');
  ok(await count('#resultBox .tile.ok') === t.word.length, 'a green tile for every letter');
  ok(await count('#dots .dot.first') === 1, 'dot marked green');
  await sleep(2200);
  t = await T(); ok(t.phase === 'answer' && !!t.word, 'auto-advanced to: ' + t.word);
  const w2 = t.word;
  await typeAnswer('zzq');
  t = await T();
  ok(t.phase === 'lockin', 'wrong answer enters lock-in');
  ok(await visible('#lockinBox') && (await text('#lockinBox')).indexOf(w2) >= 0, 'lock-in box shows the correct word');
  ok(await count('#resultBox .tile.bad') > 0, 'wrong letters marked');
  ok(await count('#resultBox .tile.miss') > 0, 'missing letters marked');
  ok(t.streak === 0 && await count('#dots .dot.miss') === 1, 'streak reset and dot marked red');
  await typeAnswer(w2);
  t = await T(); ok(t.phase === 'done' && t.pearls === before + 12, 'lock-in retype accepted for +2 (' + t.pearls + ')');
  await sleep(2200);
  t = await T(); const w3 = t.word;
  await page.click('#hintBtn'); await sleep(250);
  ok(await visible('#hintStrip') && (await text('#hintStrip .h.show')) === w3[0], 'hint reveals the first letter');
  await typeAnswer(w3);
  t = await T(); ok(t.pearls === before + 17, 'hinted answer worth 5 (' + t.pearls + ')');
  const beforeRetry = t.pearls;
  for (let i = 0; i < 14; i++) { await sleep(1500); t = await T(); if (t.screen !== 'scr-play') break; if (t.phase !== 'answer') continue; await typeAnswer(t.word); }
  await sleep(2800);
  t = await T();
  ok(t.screen === 'scr-summary', 'round ends on the summary screen');
  ok(await count('#dots .dot') === 6, 'missed word was retried at the end');
  ok(await page.evaluate(() => __spelling.G.queue[5].status === 'retry'), 'retry dot marked as a fix');
  ok((await text('#sumStats')).indexOf('of 5') >= 0, 'summary counts the 5 words');
  ok(await visible('#missedWrap') && (await text('#missedList')).indexOf(w2) >= 0, 'missed word listed');
  ok(t.level >= 1, 'reached level 1 (' + t.pearls + ' sprinkles)');
  ok(await text('#lbLevel') === 'Level ' + t.level, 'level bar updated');
  await page.click('#practiceMissed'); await sleep(600);
  t = await T(); ok(t.word === w2 && t.screen === 'scr-play', 'practice round starts with the missed word');
  await typeAnswer(w2); await sleep(2800);
  t = await T(); ok(t.screen === 'scr-summary', 'practice round ends');

  console.log('6. Levels, scenery, outfits');
  ok(await count('#scene [data-lv="1"].on') > 0, 'level 1 scenery visible');
  ok(await count('#scene [data-lv="10"].on') === 0, 'level 10 scenery hidden');
  await page.click('#sumHome'); await sleep(400);
  const unlocked = await count('.level-card:not(.locked)');
  ok(unlocked === t.level + 1, 'unlocked level cards: ' + unlocked);
  ok(await count('.level-card') === t.level + 2, 'only earned levels plus one Surprise card are shown');
  ok((await text('.level-card.mystery .lc-name')) === 'Surprise!' && (await text('.level-card.mystery .lc-lv')) === 'Level ' + (t.level + 1), 'next level is a surprise card');
  ok((await text('#levelGrid')).indexOf('Cupcake Hat') < 0 && (await text('#levelGrid')).indexOf('Rock Candy') < 0, 'future outfits are not named');
  ok(/^Level \d+ at \d+ /.test(await text('#lbNext')), 'level bar does not name the next outfit');
  ok(await count('#axoHome .acc.on') > 0, 'outfit piece worn');
  await page.click('.level-card[data-lv="0"]'); await sleep(250);
  ok(await count('#axoHome .acc.on') === 0, 'Start look removes the outfit');
  await page.click('.level-card[data-lv="1"]'); await sleep(250);
  ok(await count('#axoHome .acc.on') > 0, 'level 1 look restored');

  console.log('7. Tile Time');
  await page.click('.mode-btn[data-mode="tiles"]'); await sleep(700);
  t = await T(); ok(await visible('#tileArea') && await count('#tiles .tile.pick') === t.word.length, 'tiles laid out for: ' + t.word);
  const p0 = t.pearls;
  for (const ch of t.word) { const h = await page.evaluateHandle(ch => Array.from(document.querySelectorAll('#tiles .tile.pick:not(.used)')).find(b => b.textContent === ch), ch); await h.asElement().click(); await sleep(90); }
  await sleep(800); t = await T();
  ok(t.phase === 'done' && t.pearls === p0 + 10, 'tiles answer accepted (+10)');
  await page.click('#quitBtn'); await sleep(300);
  ok(await visible('#scr-home'), 'Home button leaves the round');

  console.log('8. Word list');
  await page.click('.mode-btn[data-mode="list"]'); await sleep(400);
  ok(await count('#wordList .word-row') === 50, '50 words in the 4th grade list');
  ok(await page.$eval('#chipCrossed', el => el.hidden), 'crossed-off chip hidden for 4th grade');
  ok(await count('#wordList .word-row[data-w="December"]') === 1, 'December listed with its capital');
  await page.click('#wordList .word-row[data-w="December"]'); await sleep(250);
  ok((await text('#wordDetail')).indexOf('twelfth') >= 0, 'word detail shows the meaning');
  await page.click('#wordsHome'); await sleep(300);

  console.log('9. December accepts lowercase');
  await page.evaluate(() => { const w = __spelling.WORDS4.find(x => x.w === 'December'); __spelling.startRound('spell', [w]); });
  await sleep(500); await typeAnswer('december');
  t = await T(); ok(t.phase === 'done', 'lowercase december accepted');
  await page.evaluate(() => document.getElementById('quitBtn').click()); await sleep(300);
  await page.evaluate(() => { const w = __spelling.WORDS4.find(x => x.w === 'kelp'); __spelling.startRound('spell', [w]); });
  await sleep(500); await typeAnswer('KeLP');
  t = await T(); ok(t.phase === 'done', 'mixed-case KeLP accepted');
  ok(await page.$eval('#spellInput', el => getComputedStyle(el).textTransform === 'none'), 'spelling box keeps what she types');
  await page.evaluate(() => document.getElementById('quitBtn').click()); await sleep(300);
  await page.evaluate(() => { const w = __spelling.WORDS4.find(x => x.w === 'December'); __spelling.startRound('spell', [w]); });
  await sleep(500); await typeAnswer('DECEMBAR');
  ok((await T()).phase === 'lockin' && await count('#resultBox .tile.ok') === 7, 'diff ignores case: 7 letters match in DECEMBAR');
  await page.evaluate(() => document.getElementById('quitBtn').click()); await sleep(300);

  console.log('10. Switching players and persistence');
  const charliePearls = (await T()).pearls;
  await page.click('#switchBtn'); await sleep(350);
  ok(await visible('#scr-profiles'), 'switch shows the player screen');
  ok((await text('.profile-card[data-id="charlie"] .pc-sub')).indexOf('Level ' + t.level) >= 0, 'Charlie card shows her level');
  await page.click('.profile-card[data-id="riley"]'); await sleep(500);
  ok(await world() === 'lagoon' && await text('#playerName') === 'Riley', 'Riley lands in the lagoon');
  ok((await T()).pearls === 0, 'Riley starts at 0 pearls');
  ok(await text('#axoNameHome') === 'Axolotl', 'Riley default character');
  ok(await count('.char-chip') === 6 && await count('.char-chip[data-char="penguin"]') === 1, 'six lagoon characters');
  await page.click('.mode-btn[data-mode="list"]'); await sleep(350);
  ok(await count('#wordList .word-row') === 50 && !(await page.$eval('#chipCrossed', el => el.hidden)), '3rd grade list with the crossed-off chip');
  await page.click('#chipCrossed'); await sleep(250);
  ok(await count('#wordList .word-row') === 17, '17 crossed-off words');
  await page.click('#wordsHome'); await sleep(250);
  await page.click('#gradeSeg .seg-btn[data-g="4"]'); await away();
  ok(await world() === 'lagoon' && (await T()).grade === '4', 'Riley can use the 4th grade list and stays in the lagoon');
  await page.click('#gradeSeg .seg-btn[data-g="3"]'); await away();
  await page.click('#switchBtn'); await sleep(300); await page.click('.profile-card[data-id="charlie"]'); await sleep(500);
  ok((await T()).pearls === charliePearls && await world() === 'candy', 'Charlie progress intact after switching');
  await page.reload({ waitUntil: 'load' }); await sleep(700);
  ok(await visible('#scr-profiles'), 'reload shows the player screen');
  await page.click('.profile-card[data-id="charlie"]'); await sleep(500);
  ok((await T()).pearls === charliePearls, 'Charlie progress survives a reload');
  ok(await text('#axoNameHome') === 'Cupcake', 'character choice survives a reload');

  console.log('10b. Saves are safe before a player is picked');
  const keepPearls = (await T()).pearls;
  await page.evaluate(() => { __spelling.G.cur = null; }); await page.reload({ waitUntil: 'load' }); await sleep(600);
  await page.click('#soundBtn'); await sleep(150); await page.click('#soundBtn'); await sleep(150);
  await page.click('.profile-card[data-id="charlie"]'); await sleep(500);
  ok((await T()).pearls === keepPearls, 'sound button on the player screen does not wipe the last save');
  await page.click('.mode-btn[data-mode="list"]'); await sleep(300); await page.click('#wordList .word-row'); await sleep(200);
  await page.click('#wordsHome'); await sleep(200); await page.click('#switchBtn'); await sleep(300);
  await page.click('.profile-card[data-id="riley"]'); await sleep(400); await page.click('.mode-btn[data-mode="list"]'); await sleep(300);
  ok((await text('#wordDetail')).indexOf('Tap a word') >= 0 && await count('#wordList .word-row.on') === 0, 'word detail does not carry over to the other player');
  await page.click('#wordsHome'); await sleep(200); await page.click('#switchBtn'); await sleep(300); await page.click('.profile-card[data-id="charlie"]'); await sleep(400);
  await page.evaluate(() => { const w = __spelling.WORDS4.find(x => x.w === 'kelp'); __spelling.startRound('tiles', [w]); }); await sleep(400);
  await page.evaluate(() => { const L = __spelling.G.tileLetters, want = 'kelp'.split(''), used = []; want.forEach(ch => { const i = L.findIndex((c, j) => c === ch && used.indexOf(j) < 0); used.push(i); document.querySelector('#tiles .tile.pick[data-i="' + i + '"]').click(); }); document.querySelector('#slots .tile.slot[data-i="3"]').click(); });
  await sleep(600);
  ok((await T()).phase === 'answer', 'removing a tile right after filling the row cancels the auto-check');
  await page.evaluate(() => document.getElementById('quitBtn').click()); await sleep(300);

  console.log('10c. Two tabs never overwrite each other');
  const extraTabs = [];
  const stored = async () => { await sleep(900); await waitSync(page); for (const pg of extraTabs) await waitSync(pg); return recOf(cloud.store.charlie.state).pearls; };
  const q0 = await stored();
  const page2 = await browser.newPage(); extraTabs.push(page2); await cloud.attach(page2); await page2.setViewport({ width: 1200, height: 900 });
  await page2.goto(URL, { waitUntil: 'load' }); await sleep(500);
  await page2.$eval('.profile-card[data-id="charlie"]', el => el.click()); await sleep(400);
  const answerIn = (pg, word) => pg.evaluate((word) => { const w = __spelling.WORDS4.find(x => x.w === word); __spelling.startRound('spell', [w]); document.getElementById('spellInput').value = w.w; document.getElementById('checkBtn').click(); document.getElementById('quitBtn').click(); }, word);
  await answerIn(page, 'kelp'); await sleep(300);
  await page2.evaluate(() => { document.dispatchEvent(new Event('visibilitychange')); });
  await answerIn(page2, 'lunar'); await sleep(300);
  ok(await stored() === q0 + 20, 'answers from both tabs count (' + q0 + ' -> ' + (await stored()) + ')');
  await page.evaluate(() => { __spelling.SW().pearls -= 5000; });
  await answerIn(page2, 'elite'); await sleep(300);
  ok(await stored() === q0 + 30, 'a tab holding old numbers cannot lower the save');
  await page2.$eval('#gradeSeg .seg-btn[data-g="3"]', el => el.click()); await sleep(200); await page2.$eval('#gradeSeg .seg-btn[data-g="4"]', el => el.click()); await sleep(200);
  ok(await stored() === q0 + 30, 'switching grades in another tab keeps the progress');
  await page2.close();
  await page.reload({ waitUntil: 'load' }); await sleep(500); await page.click('.profile-card[data-id="charlie"]'); await sleep(400);

  console.log('10d. Vera and the rainforest');
  await page.click('#switchBtn'); await sleep(300);
  await page.hover('.profile-card[data-id="vera"]'); await sleep(250);
  ok(await world() === 'canopy' && await text('#brand') === 'Spelling Canopy', 'hovering Vera previews the rainforest');
  await away();
  await page.click('.profile-card[data-id="vera"]'); await sleep(500);
  ok(await world() === 'canopy' && await text('#playerName') === 'Vera', 'Vera lands in the rainforest');
  ok(await text('#axoNameHome') === 'Sloth' && await attr('.char-chip.on', 'data-char') === 'sloth', 'Vera starts as a sloth');
  ok(await count('.char-chip') === 6, 'six rainforest characters');
  ok(await attr('.seg-btn.on', 'data-g') === '4', 'Vera on the 4th grade list');
  await page.hover('#gradeSeg .seg-btn[data-g="3"]'); await sleep(250);
  ok(await world() === 'canopy', 'grade hover keeps the rainforest for Vera');
  await page.click('#gradeSeg .seg-btn[data-g="3"]'); await away();
  ok(await world() === 'canopy' && await text('#gradeLabel') === '3rd grade', '3rd grade words, still the rainforest');
  await page.click('#gradeSeg .seg-btn[data-g="4"]'); await away();
  for (const c of ['toucan', 'monkey', 'treefrog', 'jaguar', 'gotter', 'sloth']) { await page.click('.char-chip[data-char="' + c + '"]'); await sleep(120); }
  ok(await text('#axoNameHome') === 'Sloth' && await count('#axoHome svg ellipse') > 5, 'every rainforest character draws');
  await page.evaluate(() => { const w = __spelling.WORDS3.find(x => x.w === 'sloth'); __spelling.startRound('spell', [w]); }); await sleep(500);
  ok(!/sloth/i.test(await page.evaluate(() => document.getElementById('app').innerText)), 'the word sloth is not shown while it is being tested');
  await typeAnswer('sloth'); t = await T();
  ok(t.phase === 'done' && t.pearls === 10, 'Vera earns 10 leaves');
  ok(!/sloth/i.test(await page.evaluate(() => document.getElementById('app').innerText)), 'praise never names the word');
  await page.evaluate(() => document.getElementById('quitBtn').click()); await sleep(300);
  ok((await T()).pearls === 10 && recOf(await online('vera')).pearls === 10, 'Vera save is separate');
  await page.evaluate(() => { __spelling.SW().pearls = 1400; __spelling.save(); }); await page.reload({ waitUntil: 'load' }); await sleep(500);
  await page.click('.profile-card[data-id="vera"]'); await sleep(600);
  ok(await text('#lbLevel') === 'Level 10' && await count('#scene [data-lv="10"].on') > 0 && await count('#axoHome .acc.on') >= 5, 'rainforest level 10 shows its scenery and outfit');
  await page.screenshot({ path: 'vera-10.png' });
  await page.click('#switchBtn'); await sleep(300); await page.click('.profile-card[data-id="charlie"]'); await sleep(500);

  console.log('10e. Cora and the ocean');
  await page.click('#switchBtn'); await sleep(300);
  await page.hover('.profile-card[data-id="cora"]'); await sleep(250);
  ok(await world() === 'ocean' && await text('#brand') === 'Spelling Ocean', 'hovering Cora previews the ocean');
  await away();
  await page.click('.profile-card[data-id="cora"]'); await sleep(500);
  ok(await world() === 'ocean' && await text('#playerName') === 'Cora', 'Cora lands in the ocean');
  ok(await text('#axoNameHome') === 'Jellyfish' && await attr('.char-chip.on', 'data-char') === 'jellyfish', 'Cora starts as a jellyfish');
  ok(await count('.char-chip') === 6, 'six ocean characters');
  ok(await attr('.seg-btn.on', 'data-g') === '4', 'Cora on the 4th grade list');
  await page.hover('#gradeSeg .seg-btn[data-g="3"]'); await sleep(250);
  ok(await world() === 'ocean', 'grade hover keeps the ocean for Cora');
  await page.click('#gradeSeg .seg-btn[data-g="3"]'); await away();
  ok(await world() === 'ocean' && await text('#gradeLabel') === '3rd grade', '3rd grade words, still the ocean');
  await page.click('#gradeSeg .seg-btn[data-g="4"]'); await away();
  for (const c of ['octopus', 'seahorse', 'clownfish', 'narwhal', 'pufferfish', 'jellyfish']) { await page.click('.char-chip[data-char="' + c + '"]'); await sleep(120); }
  ok(await text('#axoNameHome') === 'Jellyfish' && await count('#axoHome svg path') > 5, 'every ocean character draws');
  await page.evaluate(() => { const w = __spelling.WORDS4.find(x => x.w === 'lunar'); __spelling.startRound('spell', [w]); }); await sleep(500);
  await typeAnswer('lunar'); t = await T();
  ok(t.phase === 'done' && t.pearls === 10, 'Cora earns 10 bubbles');
  await page.evaluate(() => document.getElementById('quitBtn').click()); await sleep(300);
  ok((await T()).pearls === 10 && recOf(await online('cora')).pearls === 10, 'Cora save is separate');
  await page.evaluate(() => { __spelling.SW().pearls = 1400; __spelling.save(); }); await page.reload({ waitUntil: 'load' }); await sleep(500);
  await page.click('.profile-card[data-id="cora"]'); await sleep(600);
  ok(await text('#lbLevel') === 'Level 10' && await count('#scene [data-lv="10"].on') > 0 && await count('#axoHome .acc.on') >= 5, 'ocean level 10 shows its scenery and outfit');
  await page.screenshot({ path: 'cora-10.png' });
  await page.evaluate(() => document.getElementById('resetBtn').click()); await sleep(200); await page.evaluate(() => document.getElementById('resetYes').click()); await sleep(400);
  ok(await world() === 'ocean' && await count('.char-chip[data-char="jellyfish"]') === 1 && await text('#lbLevel') === 'Level 0', 'reset keeps Cora in the ocean');
  await page.click('#switchBtn'); await sleep(300); await page.click('.profile-card[data-id="charlie"]'); await sleep(500);

  console.log('11. Sound toggle and reset');
  await page.click('#soundBtn'); await sleep(100);
  ok(await page.$eval('#soundBtn', el => el.classList.contains('off')), 'sound off');
  await page.click('#soundBtn'); await sleep(100);
  await page.click('#resetBtn'); await sleep(150); ok(await visible('#resetConfirm'), 'reset asks first');
  await page.click('#resetNo'); await sleep(150); ok(!(await visible('#resetConfirm')), 'Keep them cancels');
  await page.click('#resetBtn'); await sleep(100); await page.click('#resetYes'); await sleep(400);
  ok((await T()).pearls === 0 && await text('#lbLevel') === 'Level 0', 'reset clears progress');
  ok(await text('#axoNameHome') === 'Cupcake' && await world() === 'candy', 'reset keeps character and grade');

  console.log('12. Phone layout');
  await page.setViewport({ width: 390, height: 844, isMobile: true, hasTouch: true }); await sleep(500);
  const fits = () => page.evaluate(() => { const m = document.getElementById('main'); return document.documentElement.scrollWidth <= window.innerWidth + 1 && m.scrollWidth <= m.clientWidth + 1; });
  ok(await fits(), 'home fits at 390px wide');
  await tap('.mode-btn[data-mode="spell"]'); await sleep(600);
  ok(await fits(), 'play screen fits');
  ok(await page.$eval('#checkBtn', el => el.getBoundingClientRect().height >= 44), 'Check button is tap-sized');
  ok(await page.$eval('#spellInput', el => el.getBoundingClientRect().width > 250), 'spelling box is wide');
  await tap('#quitBtn'); await sleep(250);
  await tap('.mode-btn[data-mode="list"]'); await sleep(350);
  ok(await fits(), 'word list fits');
  await tap('#wordsHome'); await sleep(250);
  await tap('#switchBtn'); await sleep(300);
  ok(await fits(), 'player screen fits');
  console.log('12b. Keyboard-height view');
  await tap('.profile-card[data-id="charlie"]'); await sleep(500);
  await page.setViewport({ width: 390, height: 430, isMobile: true, hasTouch: true }); await sleep(500);
  await tap('.mode-btn[data-mode="spell"]'); await sleep(800);
  const within = (sel) => page.$eval(sel, el => { const r = el.getBoundingClientRect(); return r.height > 0 && r.top >= -1 && r.bottom <= window.innerHeight + 1; });
  ok(await page.evaluate(() => document.getElementById('app').getBoundingClientRect().height <= window.innerHeight + 1), 'app fits the visible height');
  ok(await within('#spellInput'), 'spelling box visible in a keyboard-sized view');
  ok(await within('#checkBtn'), 'Check button visible in a keyboard-sized view');
  ok(await page.$eval('.levelbar', el => el.offsetParent === null), 'level bar hidden during play on phones');
  await typeAnswer('zzq'); await sleep(700);
  ok(await within('#resultBox'), 'feedback visible after a miss in a keyboard-sized view');
  ok(await within('#spellInput'), 'spelling box still reachable for the lock-in retype');
  t = await T(); await typeAnswer(t.word); await sleep(600);
  ok((await T()).phase === 'done' && await page.$eval('#spellInput', el => el.readOnly && document.activeElement === el), 'input stays focused (keyboard stays open) after an answer');
  await tap('#quitBtn'); await sleep(300);

  console.log('12c. Every word in both lists, both modes');
  await page.setViewport({ width: 1200, height: 900 }); await sleep(300);
  const sweep = await page.evaluate(() => {
    const H = __spelling, bad = [], G = () => H.G, click = () => document.getElementById('checkBtn').click();
    const order = (word) => { const used = [], L = G().tileLetters; return word.toLowerCase().split('').map(ch => { for (let i = 0; i < L.length; i++) { if (L[i] === ch && used.indexOf(i) < 0) { used.push(i); return i; } } return -1; }); };
    for (const w of H.WORDS3.concat(H.WORDS4)) {
      H.startRound('spell', [w]); document.getElementById('spellInput').value = w.w.toUpperCase(); click();
      if (G().phase !== 'done') bad.push('spell upper: ' + w.w);
      H.startRound('spell', [w]); document.getElementById('spellInput').value = ' ' + w.w.toLowerCase() + ' '; click();
      if (G().phase !== 'done') bad.push('spell lower: ' + w.w);
      H.startRound('tiles', [w]);
      if (G().tileLetters.join('') === w.w.toLowerCase() && w.w.length > 2) bad.push('tiles not scrambled: ' + w.w);
      if (G().tileLetters.some(c => c !== c.toLowerCase())) bad.push('tile has a capital: ' + w.w);
      let o = order(w.w); if (o.indexOf(-1) >= 0) { bad.push('tiles missing letters: ' + w.w); continue; }
      G().tileSel = o; click(); if (G().phase !== 'done') bad.push('tiles correct: ' + w.w);
      H.startRound('tiles', [w]); o = order(w.w); const rev = o.slice().reverse();
      if (rev.map(i => G().tileLetters[i]).join('') !== w.w.toLowerCase()) { G().tileSel = rev; click(); if (G().phase !== 'lockin') bad.push('tiles wrong -> lockin: ' + w.w); o = order(w.w); G().tileSel = o; click(); if (G().phase !== 'done') bad.push('tiles lock-in retype: ' + w.w); }
      const re = new RegExp(w.w, 'ig'); if (!re.test(w.s)) bad.push('sentence lacks the word: ' + w.w);
      if (w.w !== w.w.toLowerCase() && w.w !== 'December') bad.push('unexpected capital in word: ' + w.w);
      const pre = w.w.toLowerCase().slice(0, Math.min(5, w.w.length));
      if (w.d.toLowerCase().indexOf(pre) >= 0) bad.push('meaning gives it away: ' + w.w);
      if (w.s.replace(new RegExp(w.w, 'ig'), '____').toLowerCase().indexOf(pre) >= 0) bad.push('blanked sentence gives it away: ' + w.w);
    }
    return bad;
  });
  ok(sweep.length === 0, 'all 100 words pass upper/lower typing, tiles, and tile lock-in' + (sweep.length ? ': ' + sweep.slice(0, 8).join(' | ') : ''));
  await page.evaluate(() => { const b = document.getElementById('quitBtn'); b.click(); }); await sleep(400);
  await page.evaluate(() => { const w = __spelling.WORDS4.find(x => x.w === 'December'); __spelling.startRound('tiles', [w]); }); await sleep(400);
  await page.click('#hintBtn'); await sleep(200);
  ok(await count('#tiles .tile.pick.glow') === 1 && (await text('#tiles .tile.pick.glow')) === 'd', 'December hint glows the lowercase d tile');
  await page.evaluate(() => document.getElementById('quitBtn').click()); await sleep(300);
  console.log('12d. Charlie restore');
  await page.setViewport({ width: 1200, height: 900 });
  await waitSync(page); delete cloud.store.charlie; delete cloud.store.riley;
  await _reload({ waitUntil: 'load' }); await sleep(600);
  ok((await text('.profile-card[data-id="charlie"] .pc-sub')).indexOf('Level 10') >= 0, 'Charlie card shows level 10 after the restore');
  await page.click('.profile-card[data-id="charlie"]'); await sleep(500);
  ok((await T()).pearls >= 1458 && await text('#lbLevel') === 'Level 10' && await world() === 'candy', 'Charlie is back at level 10 in the candy world');
  ok((await online('charlie')).restoredId === 'r20260927', 'restore is saved online and applies only once');

  await waitSync(page); cloud.store.riley = { rev: 9, state: { restoredId: 'r20260927b', worlds: { lagoon: { pearls: 360, wearLevel: null }, candy: { pearls: 0, wearLevel: null } } } }; await _reload({ waitUntil: 'load' }); await sleep(500);
  ok((await text('.profile-card[data-id="riley"] .pc-sub')).indexOf('Level 3') >= 0, 'the level 5 raise is undone: Riley back at level 3, keeping 10 earned since');
  await page.click('.profile-card[data-id="riley"]'); await sleep(400); ok((await T()).pearls === 171, 'Riley has 171 pearls');

  console.log('12e. Levels 11-20 need mastered words');
  const pickPlayer = async (id) => { await page.reload({ waitUntil: 'load' }); await sleep(500); await page.click('.profile-card[data-id="' + id + '"]'); await sleep(500); };
  const master = (list, n) => page.evaluate((list, n) => { const L = __spelling[list]; for (let i = 0; i < n; i++) __spelling.S.words[L[i].w] = { streak: 3, right: 3, wrong: 0, seen: 3, mastered: true }; __spelling.save(); }, list, n);
  await page.click('#switchBtn'); await sleep(300); await page.click('.profile-card[data-id="riley"]'); await sleep(400);
  await page.evaluate(() => { __spelling.S.words = {}; __spelling.S.epoch = (__spelling.S.epoch || 0) + 1; __spelling.SW().pearls = 5000; __spelling.save(); }); await pickPlayer('riley');
  ok(await text('#lbLevel') === 'Level 10' && (await text('#lbNext')).indexOf('10 words mastered') >= 0, 'plenty of pearls but no mastered words stops at level 10');
  ok((await text('.level-card.mystery .lc-sub')).indexOf('10 mastered') >= 0, 'surprise card names the mastery goal');
  await master('WORDS3', 25); await pickPlayer('riley');
  ok(await text('#lbLevel') === 'Level 14' && await count('#scene [data-lv="14"].on') > 0 && await count('#axoHome .acc.on[data-lv="14"]') === 1, '25 mastered words reach level 14 with its scenery and extra');
  ok(await count('#axoHome .acc.on[data-lv="12"] ellipse') > 3, 'tiny buddy draws');
  await master('WORDS3', 50); await pickPlayer('riley');
  ok(await text('#lbLevel') === 'Level 20' && await text('#lbNext') === 'Top level reached!' && await count('#axoHome .acc.on[data-lv="20"]') === 1 && await count('#scene [data-lv="20"].on') > 0, 'all 50 mastered reaches level 20 with the trophy');
  ok(await text('#masteredCount') === '50', 'home shows 50 of 50 mastered');
  await page.click('#switchBtn'); await sleep(300); await page.click('.profile-card[data-id="vera"]'); await sleep(400);
  await page.evaluate(() => { __spelling.S.words = {}; __spelling.S.epoch = (__spelling.S.epoch || 0) + 1; __spelling.SW().pearls = 5000; __spelling.save(); }); await master('WORDS4', 25); await pickPlayer('vera');
  ok(await text('#lbLevel') === 'Level 14', 'Vera at level 14');
  await page.click('#gradeSeg .seg-btn[data-g="3"]'); await away();
  ok(await text('#lbLevel') === 'Level 14', 'switching grades never lowers the level');
  await page.click('#gradeSeg .seg-btn[data-g="4"]'); await away();
  const answer = (word, hint) => page.evaluate((word, hint) => { const w = __spelling.WORDS4.find(x => x.w === word); __spelling.startRound('spell', [w]); if (hint) document.getElementById('hintBtn').click(); document.getElementById('spellInput').value = w.w; document.getElementById('checkBtn').click(); document.getElementById('quitBtn').click(); return JSON.stringify(__spelling.S.words[w.w]); }, word, hint);
  const hinted = JSON.parse(await answer('opposite', true));
  ok(hinted.streak === 0 && !hinted.mastered, 'a hinted answer does not count toward mastery');
  await answer('opposite'); await answer('opposite'); const third = JSON.parse(await answer('opposite'));
  ok(third.mastered === true, 'three clean answers in a row master a word');
  await page.evaluate(() => { const w = __spelling.WORDS4.find(x => x.w === 'opposite'); __spelling.startRound('spell', [w]); document.getElementById('spellInput').value = 'opposit'; document.getElementById('checkBtn').click(); document.getElementById('quitBtn').click(); });
  ok(await page.evaluate(() => __spelling.S.words.opposite.mastered === true && __spelling.S.words.opposite.streak === 0), 'a later miss keeps the word mastered');
  await page.evaluate(() => { __spelling.S.words = {}; __spelling.S.epoch = (__spelling.S.epoch || 0) + 1; __spelling.SW().pearls = 1600; __spelling.save(); }); await master('WORDS4', 9); await pickPlayer('vera');
  ok(await text('#lbLevel') === 'Level 10', 'Vera at level 10 with 9 mastered');
  for (let i = 0; i < 3; i++) await answer('lunar');
  await sleep(1800);
  ok(await text('#lbLevel') === 'Level 11', 'mastering the 10th word levels up to 11');
  await page.screenshot({ path: 'lv11.png' });

  console.log('12f. Online saves only');
  const onlinePearls = (id, w) => { const x = cloud.store[id]; return x ? recOf(x.state).pearls : 0; };
  const pearlsIn = (pg, w) => pg.evaluate(w => __spelling.SW().pearls, w);
  const gameKeys = pg => pg.evaluate(() => Object.keys(localStorage).filter(k => k.indexOf('spelling-worlds') === 0));
  await sleep(700); ok(await waitSync(page), 'saves finish');
  ok(onlinePearls('vera', 'canopy') === await pearlsIn(page, 'canopy'), 'the online save of Vera matches the game (' + onlinePearls('vera', 'canopy') + ')');
  ok((await gameKeys(page)).length === 0, 'the browser holds no game state: ' + JSON.stringify(await gameKeys(page)));
  const newDevice = async () => { const ctx = await browser.createBrowserContext(); const pg = await ctx.newPage(); await cloud.attach(pg); pg.on('pageerror', e => errors.push('device pageerror: ' + e.message)); await pg.setViewport({ width: 1200, height: 900 }); return { ctx, pg }; };
  const d2 = await newDevice(), dev2 = d2.pg;
  await dev2.goto(URL, { waitUntil: 'load' }); await sleep(600);
  ok(await dev2.$eval('.profile-card[data-id="vera"] .pc-sub', e => e.textContent) === 'Level 11', 'another device shows Vera at level 11');
  await dev2.evaluate(() => __spelling.selectProfile('vera')); await sleep(300);
  ok(await pearlsIn(dev2, 'canopy') === onlinePearls('vera', 'canopy'), 'another device plays on from the online save');
  await sleep(700); await waitSync(dev2);
  ok(await dev2.$eval('#syncHome', e => !e.hidden && e.textContent === 'Saved online'), 'home says Saved online');
  await page.evaluate(() => __spelling.selectProfile('cora')); await dev2.evaluate(() => __spelling.selectProfile('cora')); await sleep(800); await waitSync(page); await waitSync(dev2);
  const c0 = onlinePearls('cora', 'ocean');
  ok(await pearlsIn(page, 'ocean') === c0 && await pearlsIn(dev2, 'ocean') === c0, 'both devices start Cora at ' + c0);
  await page.evaluate(() => { __spelling.SW().pearls += 10; __spelling.save(); });
  await dev2.evaluate(() => { __spelling.SW().pearls += 25; __spelling.save(); });
  await sleep(900); await waitSync(page); await waitSync(dev2);
  await page.evaluate(() => __spelling.net.refresh()); await dev2.evaluate(() => __spelling.net.refresh()); await sleep(400);
  ok(onlinePearls('cora', 'ocean') === c0 + 35, 'rewards from two devices at once both count (' + c0 + ' -> ' + onlinePearls('cora', 'ocean') + ')');
  ok(await pearlsIn(page, 'ocean') === c0 + 35 && await pearlsIn(dev2, 'ocean') === c0 + 35, 'both devices show the combined total');
  cloud.ctl.down = true;
  await page.evaluate(() => { __spelling.SW().pearls += 5; __spelling.save(); }); await sleep(900);
  ok(await page.$eval('#syncHome', e => !e.hidden && /reach the save server/.test(e.textContent)), 'no connection shows a clear not-saved note');
  ok(onlinePearls('cora', 'ocean') === c0 + 35 && (await gameKeys(page)).length === 0, 'nothing is kept in the browser while disconnected');
  cloud.ctl.down = false; await page.evaluate(() => __spelling.net.retry()); await sleep(600); await waitSync(page);
  ok(onlinePearls('cora', 'ocean') === c0 + 40, 'reconnecting sends the waiting progress');
  cloud.ctl.dropNextReply = true;
  await page.evaluate(() => { __spelling.SW().pearls += 7; __spelling.save(); }); await sleep(900);
  await page.evaluate(() => __spelling.net.retry()); await sleep(600); await waitSync(page);
  ok(onlinePearls('cora', 'ocean') === c0 + 47 && await pearlsIn(page, 'ocean') === c0 + 47, 'a save whose reply was lost is not counted twice (' + onlinePearls('cora', 'ocean') + ')');
  let c1 = onlinePearls('cora', 'ocean');
  cloud.ctl.delayMs = 700;
  await page.evaluate(() => { __spelling.SW().pearls += 5; __spelling.save(); }); await sleep(550);
  await page.evaluate(() => __spelling.net.refresh()); await sleep(200);
  cloud.ctl.delayMs = 0; await sleep(900); await waitSync(page); await page.evaluate(() => __spelling.net.refresh()); await sleep(300);
  ok(onlinePearls('cora', 'ocean') === c1 + 5 && await pearlsIn(page, 'ocean') === c1 + 5, 'a refresh while a save is on its way does not count it twice (' + (await pearlsIn(page, 'ocean') - c1) + ')');
  c1 = onlinePearls('cora', 'ocean');
  await dev2.evaluate(() => __spelling.net.refresh()); await sleep(300);
  cloud.ctl.dropReplies = 2;
  await page.evaluate(() => { __spelling.SW().pearls += 7; __spelling.save(); }); await sleep(800);
  await page.evaluate(() => { __spelling.SW().pearls += 3; __spelling.save(); }); await sleep(800);
  await dev2.evaluate(() => { __spelling.SW().pearls += 10; __spelling.save(); }); await sleep(800); await waitSync(dev2);
  await page.evaluate(() => { __spelling.SW().pearls += 1; __spelling.save(); }); await sleep(900); await waitSync(page);
  ok(onlinePearls('cora', 'ocean') === c1 + 21 && await pearlsIn(page, 'ocean') === c1 + 21, 'two lost replies plus another device saving: every reward counted once (' + (onlinePearls('cora', 'ocean') - c1) + ' of 21)');
  await page.evaluate(() => { document.getElementById('resetYes').click(); }); await sleep(900); await waitSync(page);
  await dev2.evaluate(() => __spelling.net.refresh()); await sleep(400);
  ok(onlinePearls('cora', 'ocean') === 0 && await pearlsIn(dev2, 'ocean') === 0, 'a reset on one device reaches the other');
  await d2.ctx.close();
  cloud.ctl.down = true;
  const d3 = await newDevice(), dev3 = d3.pg;
  await dev3.goto(URL, { waitUntil: 'load' }); await sleep(700);
  ok(await dev3.$eval('.profile-card[data-id="cora"]', e => e.disabled) && await dev3.$eval('#syncRetry', e => !e.hidden), 'without a connection the players wait, with a Try again button');
  cloud.ctl.down = false; await dev3.click('#syncRetry'); await sleep(600);
  ok(!(await dev3.$eval('.profile-card[data-id="cora"]', e => e.disabled)) && await dev3.$eval('#syncRetry', e => e.hidden), 'Try again loads the players');
  recOf(cloud.store.cora.state, 1).pearls = 20;
  await dev3.evaluate(ep => { window.__plantingOldSave = true; localStorage.setItem('spelling-worlds-cora', JSON.stringify({ epoch: ep, worlds: { ocean: { pearls: 100, wearLevel: null } }, words: { kelp: { streak: 3, right: 3, wrong: 0, seen: 3, mastered: true } } })); window.__plantingOldSave = false; }, cloud.store.cora.state.epoch || 0);
  await dev3.reload({ waitUntil: 'load' }); await sleep(900); await waitSync(dev3);
  ok(onlinePearls('cora', 'ocean') === 100 && cloud.store.cora.state.words.kelp.mastered === true, 'a save from before online saving is added to the online save once');
  ok((await gameKeys(dev3)).length === 0, 'and then removed from the browser');
  ok(await dev3.$eval('.profile-card[data-id="cora"] .pc-sub', e => e.textContent) === 'Level 2', 'Cora shows level 2 from it');
  await d3.ctx.close();
  ok(cloud.stats.realHits === 0, 'tests never reached the real save service');

  console.log('12g. Addie, the world picker, and Tile Time');
  const chooseWorld = async (look) => { await page.click('#worldBtn'); await sleep(250); await page.click('.world-chip[data-look="' + look + '"]'); await sleep(300); await page.click('#worldSave'); await sleep(1100); };
  await pickPlayer('addie');
  ok(await world() === 'bows' && await text('#brand') === 'Spelling Bows' && await count('.char-chip') === 6, 'Addie plays in the bow boutique with six characters');
  for (const id of ['bow', 'scrunchie', 'clawclip', 'starclip', 'flowerclip', 'bunnyband']) {
    await page.click('.char-chip[data-char="' + id + '"]'); await sleep(150);
    ok(await attr('.char-chip.on', 'data-char') === id && await count('#axoHome svg path, #axoHome svg ellipse, #axoHome svg circle, #axoHome svg polygon') > 4, 'bow character draws: ' + id);
  }
  await page.click('.char-chip[data-char="bow"]'); await sleep(150);
  for (const [p, lv] of [[30, 1], [350, 5], [1300, 10]]) {
    await page.evaluate(p => { __spelling.SW().pearls = p; __spelling.SW().wearLevel = null; __spelling.save(); }, p); await pickPlayer('addie');
    ok(await text('#lbLevel') === 'Level ' + lv && await count('#scene [data-lv="' + lv + '"].on') > 0 && await count('#axoHome .acc.on') > 0, 'Addie level ' + lv + ': scenery and outfit show');
  }
  await page.screenshot({ path: 'addie-10.png' });
  ok(recOf(await online('addie')).pearls === 1300, 'Addie\'s progress is saved online');
  const lvA = await text('#lbLevel'), pA = await text('#pearlCount');
  await chooseWorld('ocean');
  ok(await world() === 'ocean' && await text('#lbLevel') === 'Level 0' && await text('#pearlCount') === '0', 'picking the ocean starts Addie\'s jellyfish at level 0');
  ok(await attr('.world-chip.on', 'data-look') === 'ocean', 'the picked world is highlighted');
  ok(await text('#worldBtnName') === 'World: Ocean' && await page.$eval('#worldPanel', e => e.hidden), 'the world button names the saved world and the list is closed');
  await page.click('#worldBtn'); await sleep(250);
  ok(!(await page.$eval('#worldPanel', e => e.hidden)) && await page.$eval('#worldSave', e => e.disabled), 'the world button opens the list; Save waits for a new pick');
  await page.click('.world-chip[data-look="canopy"]'); await sleep(300);
  ok(await world() === 'canopy' && !(await page.$eval('#worldSave', e => e.disabled)) && (await online('addie')).look === 'ocean', 'trying the rainforest shows it without saving');
  await page.click('#worldCancel'); await sleep(300);
  ok(await world() === 'ocean' && await page.$eval('#worldPanel', e => e.hidden) && (await online('addie')).look === 'ocean', 'Cancel goes back to the saved world');
  await page.click('#worldBtn'); await sleep(250); await page.click('.world-chip[data-look="candy"]'); await sleep(300);
  await page.evaluate(() => __spelling.startRound('spell')); await sleep(300);
  ok(await world() === 'ocean' && (await online('addie')).look === 'ocean', 'starting a round while trying a world goes back to the saved one');
  await page.evaluate(() => document.getElementById('quitBtn').click()); await sleep(300);
  await page.click('#axoHome'); await sleep(120);
  ok(await page.$eval('#axoHome', e => e.classList.contains('spin')) && await count('.fx-heart') > 0, 'tapping the character spins it and bursts hearts');
  ok((await online('addie')).look === 'ocean', 'the world pick is saved online');
  await pickPlayer('addie');
  ok(await world() === 'ocean' && await text('#lbLevel') === 'Level 0', 'the pick comes back after a reload');
  await chooseWorld('bows');
  ok(await world() === 'bows' && await text('#lbLevel') === lvA && await text('#pearlCount') === pA, 'and her bow is still at its own level with its own rewards');
  await pickPlayer('charlie'); const lvC = await text('#lbLevel');
  await chooseWorld('bows');
  ok(await world() === 'bows' && await text('#lbLevel') === 'Level 0', 'Charlie starts the bow boutique at level 0');
  await page.screenshot({ path: 'charlie-bows.png' });
  await chooseWorld('candy');
  ok(await world() === 'candy' && await text('#lbLevel') === lvC, 'and goes back to the candy world at her own level');
  await pickPlayer('addie');
  const tileAnswer = word => page.evaluate(word => { const w = __spelling.WORDS3.find(x => x.w === word); __spelling.startRound('tiles', [w]); const G = __spelling.G, used = [];
    G.tileSel = w.w.split('').map(ch => { const i = G.tileLetters.findIndex((c, j) => c === ch && used.indexOf(j) < 0); used.push(i); return i; });
    document.getElementById('checkBtn').click(); document.getElementById('quitBtn').click(); }, word);
  const spellAnswer = word => page.evaluate(word => { const w = __spelling.WORDS3.find(x => x.w === word); __spelling.startRound('spell', [w]); document.getElementById('spellInput').value = w.w; document.getElementById('checkBtn').click(); document.getElementById('quitBtn').click(); }, word);
  const pT0 = await page.evaluate(() => __spelling.SW().pearls);
  for (let i = 0; i < 4; i++) { await tileAnswer('bamboo'); await sleep(150); }
  ok(await page.evaluate(() => { const st = __spelling.S.words.bamboo; return !st.mastered && st.streak === 0 && st.right === 4; }), 'four right in Tile Time do not master a word');
  ok(await page.evaluate(() => __spelling.SW().pearls) > pT0, 'Tile Time still earns rewards');
  for (let i = 0; i < 3; i++) { await spellAnswer('bamboo'); await sleep(150); }
  ok(await page.evaluate(() => __spelling.S.words.bamboo.mastered === true), 'three right in Spell It master it');
  await page.evaluate(() => { const w = __spelling.WORDS3.find(x => x.w === 'bamboo'); __spelling.startRound('tiles', [w]); __spelling.G.tileSel = [0]; document.getElementById('checkBtn').click(); document.getElementById('quitBtn').click(); });
  ok(await page.evaluate(() => __spelling.S.words.bamboo.mastered === true && __spelling.S.words.bamboo.streak === 3), 'a Tile Time miss leaves mastery alone');

  console.log('12h. Amy and the boba shop');
  await pickPlayer('amy');
  ok(await text('.home-badge') === '4th grade words', 'Amy starts on the 4th grade words');
  ok(await world() === 'boba' && await text('#brand') === 'Spelling Boba' && await count('.char-chip') === 6, 'Amy plays in the boba shop with six characters');
  for (const id of ['milktea', 'taro', 'matcha', 'strawberrytea', 'mangoslush', 'bobapearl']) {
    await page.click('.char-chip[data-char="' + id + '"]'); await sleep(150);
    ok(await attr('.char-chip.on', 'data-char') === id && await count('#axoHome svg path, #axoHome svg ellipse, #axoHome svg circle, #axoHome svg rect') > 4, 'boba character draws: ' + id);
  }
  await page.click('.char-chip[data-char="milktea"]'); await sleep(150);
  for (const [p, lv] of [[30, 1], [480, 6], [1300, 10]]) {
    await page.evaluate(p => { __spelling.SW().pearls = p; __spelling.SW().wearLevel = null; __spelling.save(); }, p); await pickPlayer('amy');
    ok(await text('#lbLevel') === 'Level ' + lv && await count('#scene [data-lv="' + lv + '"].on') > 0 && await count('#axoHome .acc.on') > 0, 'Amy level ' + lv + ': scenery and outfit show');
  }
  await page.screenshot({ path: 'amy-10.png' });
  ok(recOf(await online('amy')).pearls === 1300, 'Amy\'s progress is saved online');
  ok(await count('.world-chip') === 6 && await count('.world-chip[data-look="boba"]') === 1, 'the boba shop is in the world picker');
  await pickPlayer('vera'); const lvV = await text('#lbLevel');
  await chooseWorld('boba');
  ok(await world() === 'boba' && await text('#lbLevel') === 'Level 0', 'Vera starts the boba shop at level 0');
  await chooseWorld('canopy');
  ok(await world() === 'canopy' && await text('#lbLevel') === lvV, 'and her rainforest level is still there');

  console.log('12i. Online only: nothing is kept in the browser');
  {
    const src = require('fs').readFileSync(path.resolve(process.argv[2]), 'utf8');
    const uses = (src.match(/localStorage|sessionStorage|indexedDB|document\.cookie|caches\.|setItem|openDatabase/g) || []);
    ok(!/setItem|sessionStorage|indexedDB|document\.cookie|caches\.|openDatabase/.test(src), 'the game code never writes browser storage, cookies, IndexedDB, or caches');
    ok(uses.length === 2 && /function importOld\(\)\{ var ls=null; try\{ ls=window\.localStorage;/.test(src) && /localStorage\.removeItem\(imported\[id\]\)/.test(src), 'the only browser storage code is the one-time pickup of old saves (read, then delete)');
    ok(cloud.storageWrites.length === 0, 'no browser storage writes during the whole run' + (cloud.storageWrites.length ? ': ' + cloud.storageWrites.slice(0, 5).join(', ') : ''));
    ok((await page.evaluate(() => Object.keys(localStorage).length + Object.keys(sessionStorage).length + document.cookie.length)) === 0, 'browser storage and cookies are empty');
    /* a device where browser storage is blocked entirely still plays and saves */
    const ctx = await browser.createBrowserContext(); const dev = await ctx.newPage(); await cloud.attach(dev);
    dev.on('pageerror', e => errors.push('no-storage pageerror: ' + e.message));
    await dev.evaluateOnNewDocument(() => { ['localStorage', 'sessionStorage'].forEach(k => Object.defineProperty(window, k, { get() { throw new Error(k + ' blocked'); } })); });
    await dev.setViewport({ width: 1200, height: 900 }); await dev.goto(URL, { waitUntil: 'load' }); await sleep(700);
    const before = recOf(cloud.store.riley.state).pearls;
    await dev.evaluate(() => __spelling.selectProfile('riley')); await sleep(300);
    await dev.evaluate(() => { const w = __spelling.WORDS3.find(x => x.w === 'breeze'); __spelling.startRound('spell', [w]); document.getElementById('spellInput').value = w.w; document.getElementById('checkBtn').click(); document.getElementById('quitBtn').click(); });
    await sleep(1200); await waitSync(dev);
    ok(recOf(cloud.store.riley.state).pearls === before + 10, 'with browser storage blocked, a correct answer still saves online (+10)');
    await dev.reload({ waitUntil: 'load' }); await sleep(700); await dev.evaluate(() => __spelling.selectProfile('riley')); await sleep(300);
    ok(await dev.evaluate(() => __spelling.SW().pearls) === before + 10, 'and comes back from the save service after a reload');
    await ctx.close();
  }

  console.log('12j. Every character has its own level');
  {
    const L = require('../worker/src/logic.mjs');
    const mig = await page.evaluate(() => [__spelling.migrateChars({ theme: 'boba', look: 'lagoon', charLagoon: 'turtle', worlds: { boba: { pearls: 295, wearLevel: null }, lagoon: { pearls: 0, wearLevel: null } } }),
      __spelling.migrateChars({ theme: 'candy', look: 'candy', charCandy: 'icecream', worlds: { lagoon: { pearls: 167, wearLevel: null }, candy: { pearls: 4771, wearLevel: null } } })]);
    ok(JSON.stringify(mig[0]) === JSON.stringify({ 'lagoon:turtle': { pearls: 295, wearLevel: null } }), 'an old save gives its rewards to the character the kid was playing');
    ok(mig[1]['candy:icecream'].pearls === 4771 && mig[1]['lagoon:axolotl'].pearls === 167 && Object.keys(mig[1]).length === 2, 'and each other world\'s rewards to the character picked there');
    ok(JSON.stringify(L.migrateChars({ theme: 'candy', look: 'candy', charCandy: 'icecream', worlds: { lagoon: { pearls: 167, wearLevel: null }, candy: { pearls: 4771, wearLevel: null } } })) === JSON.stringify(mig[1]), 'the save service reads old saves the same way');
    const legacy = { theme: 'ocean', charOcean: 'narwhal', worlds: { ocean: { pearls: 50, wearLevel: null } } };
    const withChars = (st, add) => { const o = JSON.parse(JSON.stringify(st)); o.chars = L.migrateChars(o); o.chars['ocean:narwhal'].pearls += add; return o; };
    const merged = L.mergeState(withChars(legacy, 10), withChars(legacy, 5), legacy);
    ok(merged.chars['ocean:narwhal'].pearls === 65, 'two devices moving the same old save over count each reward once (' + merged.chars['ocean:narwhal'].pearls + ' of 65)');
    ok(!L.lowersProgress(withChars(legacy, 0), legacy) && L.lowersProgress(withChars(legacy, -1), withChars(legacy, 0)), 'the service accepts the move and refuses a save that lowers a character');
    cloud.store.amy = { rev: 3, state: { theme: 'boba', look: 'lagoon', charLagoon: 'turtle', worlds: { boba: { pearls: 295, wearLevel: null } } } };
    await page.reload({ waitUntil: 'load' }); await sleep(600);
    ok(await page.$eval('.profile-card[data-id="amy"] .pc-sub', e => e.textContent) === 'Level 4', 'Amy keeps her level on the turtle she was playing');
    await page.click('.profile-card[data-id="amy"]'); await sleep(500);
    ok(await page.evaluate(() => __spelling.SW().pearls) === 295 && await text('#lbLevel') === 'Level 4', 'and plays on with it');
    await page.evaluate(() => { const S = __spelling.S; S.epoch = (S.epoch || 0) + 1; S.chars = {}; __spelling.SW().pearls = 3300; __spelling.WORDS4.forEach(w => { S.words[w.w] = { mastered: true, streak: 3, right: 3, wrong: 0, seen: 3 }; }); __spelling.save(); });
    await pickPlayer('amy');
    ok(await text('#lbLevel') === 'Level 20' && await text('.char-chip[data-char="turtle"] .cc-lv') === 'MAX' && await page.$eval('.char-chip[data-char="turtle"]', e => e.classList.contains('maxed')), 'a character at level 20 shows MAX');
    ok(/Maxed: 1 of 36/.test(await text('#charMax')), 'the home screen counts maxed characters (' + await text('#charMax') + ')');
    ok(await text('.char-chip[data-char="frog"] .cc-lv') === 'Lv 0', 'the other characters show their own levels');
    await page.click('.char-chip[data-char="frog"]'); await sleep(400);
    ok(await text('#lbLevel') === 'Level 0' && await text('#pearlCount') === '0', 'picking another character shows that character\'s own level');
    await page.evaluate(() => { const w = __spelling.WORDS4[0]; __spelling.startRound('spell', [w]); document.getElementById('spellInput').value = w.w; document.getElementById('checkBtn').click(); document.getElementById('quitBtn').click(); });
    await sleep(1200);
    const a = await online('amy');
    ok(a.chars['lagoon:frog'].pearls === 10 && a.chars['lagoon:turtle'].pearls === 3300, 'rewards go only to the character being played, online (frog ' + a.chars['lagoon:frog'].pearls + ', turtle ' + a.chars['lagoon:turtle'].pearls + ')');
    await page.click('.char-chip[data-char="turtle"]'); await sleep(400);
    ok(await text('#lbLevel') === 'Level 20', 'switching back shows the turtle at level 20');
    await page.reload({ waitUntil: 'load' }); await sleep(600);
    ok(await page.$eval('.profile-card[data-id="amy"] .pc-sub', e => e.textContent) === 'Level 20', 'the player card shows the level of the character being played');
  }

  console.log('12k. Say It: spell the word out loud, then confirm (fake microphone)');
  {
    await page.evaluateOnNewDocument(() => {
      window.__recs = [];
      function Fake() { this.started = false; window.__recs.push(this); }
      Fake.prototype.start = function () { this.started = true; const s = this; if (!window.__slowMic) setTimeout(() => { s.onstart && s.onstart({}); s.onaudiostart && s.onaudiostart({}); }, 0); };
      Fake.prototype.stop = Fake.prototype.abort = function () { const s = this; if (!s.started) return; s.started = false; setTimeout(() => { s.onend && s.onend({}); }, 0); };
      window.SpeechRecognition = Fake;
      window.__hear = parts => { const r = window.__recs[window.__recs.length - 1]; if (!r || !r.started) return false; const results = parts.map(p => { const a = [p.t].concat(p.alts || []).map((t, k) => ({ transcript: t, confidence: k ? 0 : (p.c != null ? p.c : 0.9) })); a.isFinal = !!p.f; return a; }); r.onresult({ resultIndex: 0, results }); return true; };
      window.__micError = code => { const r = window.__recs[window.__recs.length - 1]; if (!r || !r.started) return false; r.onerror({ error: code }); r.started = false; setTimeout(() => { r.onend && r.onend({}); }, 0); return true; };
    });
    await page.reload({ waitUntil: 'load' }); await sleep(600);
    await page.click('.profile-card[data-id="riley"]'); await sleep(500);
    ok(await count('.mode-btn') === 4 && await text('.mode-btn[data-mode="say"] .mode-name') === 'Say It', 'home has a fourth mode, Say It');
    const sayRound = word => page.evaluate(word => { const w = __spelling.WORDS3.concat(__spelling.WORDS4).find(x => x.w === word); __spelling.startRound('say', [w]); }, word);
    const hear = parts => page.evaluate(parts => window.__hear(parts), parts);
    const listening = () => page.$eval('#micBtn', el => el.classList.contains('listening'));
    const quit = async () => { await page.evaluate(() => document.getElementById('quitBtn').click()); await sleep(300); };
    const confirm = async () => { await page.click('#checkBtn'); await sleep(250); };
    await page.click('.mode-btn[data-mode="say"]'); await sleep(600);
    ok(await visible('#sayArea') && !(await visible('#spellForm')) && !(await visible('#tileArea')) && await text('#clearBtn') === 'Say it again', 'Say It shows the mic and a Say it again button');
    ok(!(await listening()), 'the mic is off until the kid taps it');
    await sayRound('bamboo'); await sleep(200);
    const s0 = await page.evaluate(() => (__spelling.S.words.bamboo || { streak: 0 }).streak || 0), p0 = (await T()).pearls;
    await page.click('#micBtn'); await sleep(60);
    ok(await listening() && /Listening/.test(await text('#micLabel')), 'tapping the mic starts listening');
    await hear([{ t: 'B A M', f: true }, { t: 'B O', f: false }]);
    ok(await count('#heard .tile') === 5 && await count('#heard .tile.dim') === 2 && (await T()).phase === 'answer', 'letters show up as they are heard, the unfinished ones faded');
    await hear([{ t: 'B A M B O O', f: true }]); await sleep(900);
    ok((await T()).phase === 'answer' && await listening(), 'the right letters are not checked until the kid confirms');
    await sleep(1800);
    ok(!(await listening()) && /what you said/.test(await text('#playBubble')) && await text('#checkBtn') === 'Yes, check it!', 'after a quiet pause the mic stops and asks "Is that what you said?"');
    await confirm(); let t = await T();
    ok(t.phase === 'done' && t.pearls === p0 + 10, '"Yes, check it!" checks the letters (+10)');
    ok(await page.evaluate(() => __spelling.S.words.bamboo.streak) === s0 + 1, 'Say It counts toward mastery');
    await quit();
    await sayRound('kelp'); await page.click('#micBtn'); await hear([{ t: 'K E', f: true }]); await sleep(100); await page.click('#micBtn'); await sleep(150);
    ok((await T()).phase === 'answer' && !(await listening()) && await text('#checkBtn') === 'Yes, check it!' && /what you said/.test(await text('#playBubble')), 'tapping the mic when done stops listening and asks, without checking');
    ok(await text('#micLabel') === 'Tap to add more letters', 'the mic offers to add more letters');
    await page.click('#micBtn'); await sleep(60); await hear([{ t: 'L P', f: true }]); await sleep(100);
    ok(await count('#heard .tile') === 4, 'tapping it again adds to the letters already heard');
    await confirm(); ok((await T()).phase === 'done', 'and the whole word checks out');
    await quit();
    await sayRound('kelp'); await page.click('#micBtn'); await hear([{ t: 'K E L B', f: true }]); await sleep(100); await page.click('#micBtn'); await sleep(100);
    await page.click('#clearBtn'); await sleep(150);
    ok(await listening() && await count('#heard .tile') === 0 && (await T()).phase === 'answer', '"Say it again" clears the letters and listens again');
    await hear([{ t: 'K E L P', f: true }]); await sleep(100); await confirm();
    ok((await T()).phase === 'done' && !(await listening()), 'Check! while listening checks what was heard');
    await quit();
    await sayRound('kelp'); await page.click('#micBtn'); await hear([{ t: 'K E L B', f: true }]); await sleep(100); await confirm();
    t = await T();
    ok(t.phase === 'lockin' && await count('#resultBox .tile.bad') === 1 && /out loud/.test(await text('#lockinBox')), 'a wrong spelling shows the diff and asks to spell it out loud again');
    ok(await count('#heard .tile') === 0 && !(await listening()) && await text('#checkBtn') === 'Check!', 'the heard letters clear for the lock-in');
    await page.click('#micBtn'); await hear([{ t: 'K E L P', f: true }]); await sleep(100); await confirm();
    ok((await T()).phase === 'done', 'spelling it out loud locks it in');
    await quit();
    const sayDone = async (word, parts) => { await sayRound(word); await page.click('#micBtn'); await sleep(40); await hear(parts); await sleep(150); await confirm(); const ph = (await T()).phase; await quit(); return ph; };
    ok(await sayDone('kelp', [{ t: 'kay E el pee', f: true }]) === 'done', 'letter names like "kay" and "pee" are heard as letters');
    ok(await sayDone('lunar', [{ t: 'lunar L U N A R lunar', f: true }]) === 'done', 'saying the word before and after the letters, bee style, is fine');
    await sayRound('lunar'); await page.click('#micBtn'); await hear([{ t: 'lunar', f: true }]); await sleep(200);
    ok((await T()).phase === 'answer' && await count('#heard .tile') === 0 && /each letter/.test(await text('#playBubble')), 'just saying the word is not spelling it');
    await page.click('#micBtn'); await sleep(100);
    ok((await T()).phase === 'answer' && /Say the letters/.test(await text('#playBubble')), 'tapping the mic with nothing heard asks for letters');
    await quit();
    await page.evaluate(() => { window.__slowMic = true; }); await sayRound('bamboo'); await page.click('#micBtn'); await sleep(60);
    ok(/ready/.test(await text('#micLabel')) && await page.$eval('#micBtn', el => el.classList.contains('warming')), 'the mic says when it is still getting ready');
    await page.evaluate(() => { const r = window.__recs[window.__recs.length - 1]; r.onaudiostart({}); }); await sleep(60);
    ok(/Listening/.test(await text('#micLabel')) && !(await page.$eval('#micBtn', el => el.classList.contains('warming'))), 'and when it is listening');
    await page.evaluate(() => { window.__slowMic = false; }); await quit();
    await sayRound('bamboo'); await page.click('#micBtn'); await sleep(60); await page.evaluate(() => window.__micError('not-allowed')); await sleep(200);
    ok(await visible('#micNotice') && /blocked/.test(await text('#micNotice')) && !(await listening()), 'a blocked mic explains itself');
    const s1 = await page.evaluate(() => __spelling.S.words.bamboo.streak);
    await page.click('#hintBtn'); await sleep(200);
    await page.click('#micBtn'); await sleep(40); await hear([{ t: 'B A M B O O', f: true }]); await sleep(100); await confirm();
    ok((await T()).phase === 'done' && await page.evaluate(() => __spelling.S.words.bamboo.streak) === s1, 'a hinted Say It answer does not count toward mastery');
    await quit();
    await page.evaluate(() => { window.SpeechRecognitionPhrase = function (p, b) { this.phrase = p; this.boost = b; }; });
    await sayRound('bamboo'); await page.click('#micBtn'); await sleep(60);
    ok(await page.evaluate(() => { const ph = window.__recs[window.__recs.length - 1].phrases; return !!ph && ph.length === 26 && ph[0].phrase === 'A' && ph[0].boost === 4; }), 'where the browser supports it, the recognizer is nudged toward letter names');
    const nRecs = await page.evaluate(() => window.__recs.length);
    await page.evaluate(() => window.__micError('phrases-not-supported')); await sleep(400);
    ok(await listening() && await page.evaluate(n => window.__recs.length === n + 1 && !window.__recs[n].phrases, nRecs), 'a recognizer that cannot take the nudge restarts and listens without it');
    await page.evaluate(() => { delete window.SpeechRecognitionPhrase; }); await quit();
    const P = (s, w) => page.evaluate((s, w) => __spelling.say.parse(s, w).letters.join(''), s, w);
    ok(await P('sea L', 'seal') === 'seal' && await P('see a tea', 'cat') === 'cat' && await P('double you', 'w') === 'w' && await P('B-A-M.', 'bamboo') === 'bam' && await P('kay eye tea ee', 'kite') === 'kite' && await P('are you', 'ru') === 'ru', 'spoken letters are read the way that best fits the word');
    const saySweep = await page.evaluate(() => { const H = __spelling, bad = []; for (const w of H.WORDS3.concat(H.WORDS4)) { H.startRound('say', [w]); document.getElementById('micBtn').click(); window.__hear([{ t: w.w.toUpperCase().split('').join(' '), f: true }]); document.getElementById('checkBtn').click(); if (H.G.phase !== 'done') bad.push(w.w); } document.getElementById('quitBtn').click(); return bad; });
    ok(saySweep.length === 0, 'every word in both lists can be spelled out loud' + (saySweep.length ? ': ' + saySweep.slice(0, 8).join(', ') : ''));
    await sleep(300);
    ok(await page.evaluate(() => { const F = window.SpeechRecognition; window.SpeechRecognition = undefined; const w = __spelling.WORDS3.find(x => x.w === 'bamboo'); __spelling.startRound('say', [w]); const vis = id => { const e = document.getElementById(id); return !e.hidden && e.offsetParent !== null; }; const r = __spelling.G.screen === 'scr-play' && !vis('micBtn') && vis('sayInput') && /voice typing/.test(document.getElementById('sayOrTxt').textContent); document.getElementById('quitBtn').click(); window.SpeechRecognition = F; return r; }), 'a browser without a recognizer still plays Say It, with voice typing only');
    console.log('12l. Say It reads the recognizer generously, and takes the device\'s voice typing');
    ok(await sayDone('bamboo', [{ t: 'BAMBOO', f: true }]) === 'done', 'the word written in capitals counts as spelled letters');
    ok(await sayDone('kelp', [{ t: 'help', f: true, alts: ['K E L P', 'kelp'] }]) === 'done', 'a lower guess from the recognizer is used when it fits the word');
    ok(await sayDone('bamboo', [{ t: 'um B A M', f: true }, { t: 'and B O O', f: true }]) === 'done', 'filler words like "um" are left out');
    ok(await sayDone('whistle', [{ t: 'double you H I S T L E', f: true }]) === 'done', '"double you" is a W');
    ok(await sayDone('cloak', [{ t: 'see L oh A okay', f: true }]) === 'done', 'letter names like "see", "oh", and "okay" are heard as letters');
    ok(await sayDone('December', [{ t: 'capital D E C E M B E R', f: true }]) === 'done', 'saying "capital" before a letter is fine');
    await page.evaluate(() => __spelling.say._android(true));
    ok(await sayDone('bamboo', [{ t: 'B A M', f: true }, { t: 'B A M', f: true, c: 0 }, { t: 'B A M B O O', f: true }]) === 'done', 'Android repeats of earlier results are not counted twice');
    ok(await sayDone('bamboo', [{ t: 'B A M B O', f: true }, { t: 'O', f: true }]) === 'done', 'a letter said twice in a row on Android still counts twice');
    await page.evaluate(() => __spelling.say._android(false));
    const kb = async (word, typed, ms) => { await sayRound(word); await page.$eval('#sayInput', (el, v) => { el.value = v; el.dispatchEvent(new Event('input', { bubbles: true })); }, typed); await sleep(ms || 1200); };
    await kb('pennies', 'P E N N I E S');
    ok(await visible('#sayInput') && (await T()).phase === 'answer' && await text('#checkBtn') === 'Yes, check it!' && /what you said/.test(await text('#playBubble')), 'voice typing in the box ("P E N N I E S") waits for the kid to confirm');
    await confirm(); ok((await T()).phase === 'done', 'and then checks'); await quit();
    await kb('safety', 'SAFETY'); await confirm(); ok((await T()).phase === 'done', 'voice typing that joins the letters in capitals counts'); await quit();
    await kb('lunar', 'el you en ay are'); await confirm(); ok((await T()).phase === 'done', 'voice typing of letter names counts'); await quit();
    await kb('lunar', 'lunar');
    ok((await T()).phase === 'answer' && await count('#heard .tile') === 0 && /each letter/.test(await text('#playBubble')), 'voice typing the whole word does not count');
    await confirm(); ok((await T()).phase === 'answer' && /whole word/.test(await text('#playBubble')), 'and Check says why');
    await quit();
    await kb('kelp', 'K E L B', 500);
    await page.focus('#sayInput'); await page.keyboard.press('Enter'); await sleep(300);
    ok((await T()).phase === 'lockin' && await page.$eval('#sayInput', el => el.value === ''), 'Enter in the box checks it, and the box clears for the lock-in');
    await quit();
    await kb('kelp', 'K E L B', 300); await page.click('#clearBtn'); await sleep(150);
    ok(await page.$eval('#sayInput', el => el.value === '' && document.activeElement === el) && !(await listening()) && await count('#heard .tile') === 0, '"Say it again" after voice typing clears the box and puts the cursor back in it');
    await quit();
    await sayRound('kelp'); await page.click('#micBtn'); await hear([{ t: 'K E', f: true }]); await sleep(100);
    await page.$eval('#sayInput', el => { el.value = 'K E L P'; el.dispatchEvent(new Event('input', { bubbles: true })); }); await sleep(300); await confirm();
    ok((await T()).phase === 'done' && !(await listening()), 'using the box turns the mic off and uses the box');
    await quit();
    const kbSweep = await page.evaluate(() => { const H = __spelling, bad = [], el = document.getElementById('sayInput'); for (const w of H.WORDS3.concat(H.WORDS4)) { H.startRound('say', [w]); el.value = w.w.toUpperCase(); el.dispatchEvent(new Event('input', { bubbles: true })); document.getElementById('checkBtn').click(); if (H.G.phase !== 'done') bad.push(w.w); } document.getElementById('quitBtn').click(); return bad; });
    ok(kbSweep.length === 0, 'every word in both lists can be spelled with voice typing' + (kbSweep.length ? ': ' + kbSweep.slice(0, 8).join(', ') : ''));
    await sleep(300);
    ok(await page.evaluate(() => { const w = __spelling.WORDS3.find(x => x.w === 'bamboo'); __spelling.S.words.bamboo = { mastered: false, streak: 2, right: 2, wrong: 0, seen: 2 }; __spelling.startRound('tiles', [w]); const G = __spelling.G, used = []; G.tileSel = w.w.split('').map(ch => { for (let i = 0; i < G.tileLetters.length; i++) { if (G.tileLetters[i] === ch && used.indexOf(i) < 0) { used.push(i); return i; } } return -1; }); document.getElementById('checkBtn').click(); const st = __spelling.S.words.bamboo; document.getElementById('quitBtn').click(); return G.phase === 'done' && st.streak === 2 && !st.mastered; }), 'Tile Time still never masters a word');
  }

  console.log('13. Errors');
  ok(errors.length === 0, 'no page errors' + (errors.length ? ': ' + errors.slice(0, 3).join(' | ') : ''));
  await browser.close();
  console.log('\n' + passes + ' passed, ' + fails + ' failed');
  process.exit(fails ? 1 : 0);
})().catch(e => { console.error('TEST CRASH', e); process.exit(2); });
