const puppeteer = require('puppeteer-core');
const path = require('path');
const CHROME = 'C:/Program Files/Google/Chrome/Application/chrome.exe';
const URL = 'file:///' + path.resolve(process.argv[2]).split(path.sep).join('/');
let fails = 0, passes = 0;
function ok(cond, msg) { if (cond) { passes++; console.log('  ok   ' + msg); } else { fails++; console.log('  FAIL ' + msg); } }
const sleep = ms => new Promise(r => setTimeout(r, ms));
(async () => {
  const browser = await puppeteer.launch({ executablePath: CHROME, headless: true, args: ['--mute-audio', '--disable-speech-api', '--disable-gpu'] });
  const page = await browser.newPage();
  const cloud = require('./mockcloud').create(); await cloud.attach(page);
  const errors = [];
  page.on('pageerror', e => errors.push('pageerror: ' + e.message));
  page.on('console', m => { if (m.type() === 'error' && !/fonts\.g|net::ERR/.test(m.text())) errors.push('console: ' + m.text()); });
  await page.setViewport({ width: 1200, height: 900 });
  await page.goto(URL, { waitUntil: 'load' });
  await sleep(300);
  await page.evaluate(() => { localStorage.setItem('spelling-worlds-charlie', JSON.stringify({ restoredId: 'r20260927' })); });
  await page.reload({ waitUntil: 'load' }); await sleep(600);
  const text = (sel) => page.$eval(sel, el => el.textContent.trim());
  const visible = (sel) => page.$eval(sel, el => !el.hidden && el.offsetParent !== null);
  const attr = (sel, a) => page.$eval(sel, (el, a) => el.getAttribute(a), a);
  const count = async (sel) => (await page.$$(sel)).length;
  const world = () => page.evaluate(() => document.documentElement.getAttribute('data-world'));
  const T = () => page.evaluate(() => ({ screen: __spelling.G.screen, word: __spelling.G.cur && __spelling.G.cur.w, phase: __spelling.G.phase, pearls: __spelling.S.worlds[__spelling.world()].pearls, streak: __spelling.G.streak, grade: __spelling.S.grade, kid: __spelling.S.kid, level: __spelling.levelFor(__spelling.S.worlds[__spelling.world()].pearls) }));
  const typeAnswer = async (w) => { await page.focus('#spellInput'); await page.type('#spellInput', w); await page.keyboard.press('Enter'); await sleep(450); };
  const away = async () => { await page.mouse.move(4, 400); await sleep(250); };
  const tap = async (sel) => { await page.$eval(sel, el => el.scrollIntoView({ block: 'center' })); await sleep(200); const r = await page.$eval(sel, el => { const b = el.getBoundingClientRect(); return { x: b.left + b.width / 2, y: b.top + b.height / 2 }; }); await page.$eval(sel, el => el.click()); await sleep(100); };

  console.log('1. Player screen');
  ok(await visible('#scr-profiles'), 'player screen shown first');
  ok(await count('.profile-card') === 4, 'four player cards');
  ok((await text('.profile-card[data-id="vera"] .pc-sub')).startsWith('4th grade'), 'Vera defaults to 4th grade');
  ok((await text('.profile-card[data-id="cora"] .pc-sub')).startsWith('4th grade'), 'Cora defaults to 4th grade');
  ok((await text('.profile-card[data-id="charlie"] .pc-sub')).startsWith('4th grade'), 'Charlie defaults to 4th grade');
  ok((await text('.profile-card[data-id="riley"] .pc-sub')).startsWith('3rd grade'), 'Riley defaults to 3rd grade');
  ok(await world() === 'lagoon', 'default look is lagoon before choosing');

  console.log('2. Hover previews on player tiles');
  await page.hover('.profile-card[data-id="charlie"]'); await sleep(250);
  ok(await world() === 'candy', 'hovering Charlie previews the candy world');
  ok(await text('#brand') === 'Spelling Sweetshop', 'brand switches on hover');
  await away();
  ok(await world() === 'lagoon', 'leaving the tile restores the lagoon');
  await page.hover('.profile-card[data-id="riley"]'); await sleep(250);
  ok(await world() === 'lagoon', 'hovering Riley shows the lagoon');
  await away();

  console.log('3. Pick Charlie');
  await page.click('.profile-card[data-id="charlie"]'); await sleep(500);
  ok(await visible('#scr-home'), 'home shown');
  ok(await world() === 'candy', 'Charlie is in the candy world');
  ok(await text('#playerName') === 'Charlie', 'playing as Charlie');
  ok(await attr('.seg-btn.on', 'data-g') === '4', '4th grade selected');
  ok(await text('#axoNameHome') === 'Gummy Bear', 'default candy character');
  ok(await text('#gradeLabel') === '4th grade', 'mastered line says 4th grade');
  await page.hover('#gradeSeg .seg-btn[data-g="3"]'); await sleep(300);
  ok(await world() === 'lagoon', 'hovering 3rd grade previews the lagoon');
  ok(await text('#axoNameHome') === 'Axolotl', 'preview swaps the character too');
  await away();
  ok(await world() === 'candy' && await text('#axoNameHome') === 'Gummy Bear', 'leaving restores candy and character');

  console.log('4. Character picker');
  await page.click('.char-chip[data-char="cupcake"]'); await sleep(300);
  ok(await text('#axoNameHome') === 'Cupcake', 'cupcake chosen');
  ok(await attr('.char-chip.on', 'data-char') === 'cupcake', 'chip highlighted');
  ok(await count('.char-chip') === 6, 'six candy characters');

  console.log('5. Spell It round: correct, wrong + lock-in, hint, retry, summary');
  await page.evaluate(() => { __spelling.S.roundLen = '5'; __spelling.save(); });
  await page.click('.mode-btn[data-mode="spell"]'); await sleep(700);
  ok(await visible('#scr-play'), 'play screen shown');
  let t = await T(); ok(!!t.word, 'a word is loaded: ' + t.word);
  ok((await text('#roundLabel')).indexOf('4th grade') >= 0, 'round label names the grade');
  ok(await count('#dots .dot') === 5, 'five progress dots');
  const before = t.pearls;
  await typeAnswer(t.word);
  t = await T();
  ok(t.phase === 'done', 'correct answer accepted');
  ok(t.pearls === before + 10, 'earned 10 (' + before + ' -> ' + t.pearls + ')');
  ok(t.streak === 1, 'streak is 1');
  ok(await count('#resultBox .tile.ok') === t.word.length, 'a green tile for every letter');
  ok(await count('#dots .dot.first') === 1, 'dot marked green');
  await sleep(2200);
  t = await T(); ok(t.phase === 'answer' && !!t.word, 'auto-advanced to: ' + t.word);
  const w2 = t.word;
  await typeAnswer('zzq');
  t = await T();
  ok(t.phase === 'lockin', 'wrong answer enters lock-in');
  ok(await visible('#lockinBox') && (await text('#lockinBox')).indexOf(w2) >= 0, 'lock-in box shows the correct word');
  ok(await count('#resultBox .tile.bad') > 0, 'wrong letters marked');
  ok(await count('#resultBox .tile.miss') > 0, 'missing letters marked');
  ok(t.streak === 0 && await count('#dots .dot.miss') === 1, 'streak reset and dot marked red');
  await typeAnswer(w2);
  t = await T(); ok(t.phase === 'done' && t.pearls === before + 12, 'lock-in retype accepted for +2 (' + t.pearls + ')');
  await sleep(2200);
  t = await T(); const w3 = t.word;
  await page.click('#hintBtn'); await sleep(250);
  ok(await visible('#hintStrip') && (await text('#hintStrip .h.show')) === w3[0], 'hint reveals the first letter');
  await typeAnswer(w3);
  t = await T(); ok(t.pearls === before + 17, 'hinted answer worth 5 (' + t.pearls + ')');
  const beforeRetry = t.pearls;
  for (let i = 0; i < 14; i++) { await sleep(1500); t = await T(); if (t.screen !== 'scr-play') break; if (t.phase !== 'answer') continue; await typeAnswer(t.word); }
  await sleep(2800);
  t = await T();
  ok(t.screen === 'scr-summary', 'round ends on the summary screen');
  ok(await count('#dots .dot') === 6, 'missed word was retried at the end');
  ok(await page.evaluate(() => __spelling.G.queue[5].status === 'retry'), 'retry dot marked as a fix');
  ok((await text('#sumStats')).indexOf('of 5') >= 0, 'summary counts the 5 words');
  ok(await visible('#missedWrap') && (await text('#missedList')).indexOf(w2) >= 0, 'missed word listed');
  ok(t.level >= 1, 'reached level 1 (' + t.pearls + ' sprinkles)');
  ok(await text('#lbLevel') === 'Level ' + t.level, 'level bar updated');
  await page.click('#practiceMissed'); await sleep(600);
  t = await T(); ok(t.word === w2 && t.screen === 'scr-play', 'practice round starts with the missed word');
  await typeAnswer(w2); await sleep(2800);
  t = await T(); ok(t.screen === 'scr-summary', 'practice round ends');

  console.log('6. Levels, scenery, outfits');
  ok(await count('#scene [data-lv="1"].on') > 0, 'level 1 scenery visible');
  ok(await count('#scene [data-lv="10"].on') === 0, 'level 10 scenery hidden');
  await page.click('#sumHome'); await sleep(400);
  const unlocked = await count('.level-card:not(.locked)');
  ok(unlocked === t.level + 1, 'unlocked level cards: ' + unlocked);
  ok(await count('.level-card') === t.level + 2, 'only earned levels plus one Surprise card are shown');
  ok((await text('.level-card.mystery .lc-name')) === 'Surprise!' && (await text('.level-card.mystery .lc-lv')) === 'Level ' + (t.level + 1), 'next level is a surprise card');
  ok((await text('#levelGrid')).indexOf('Cupcake Hat') < 0 && (await text('#levelGrid')).indexOf('Rock Candy') < 0, 'future outfits are not named');
  ok(/^Level \d+ at \d+ /.test(await text('#lbNext')), 'level bar does not name the next outfit');
  ok(await count('#axoHome .acc.on') > 0, 'outfit piece worn');
  await page.click('.level-card[data-lv="0"]'); await sleep(250);
  ok(await count('#axoHome .acc.on') === 0, 'Start look removes the outfit');
  await page.click('.level-card[data-lv="1"]'); await sleep(250);
  ok(await count('#axoHome .acc.on') > 0, 'level 1 look restored');

  console.log('7. Tile Time');
  await page.click('.mode-btn[data-mode="tiles"]'); await sleep(700);
  t = await T(); ok(await visible('#tileArea') && await count('#tiles .tile.pick') === t.word.length, 'tiles laid out for: ' + t.word);
  const p0 = t.pearls;
  for (const ch of t.word) { const h = await page.evaluateHandle(ch => Array.from(document.querySelectorAll('#tiles .tile.pick:not(.used)')).find(b => b.textContent === ch), ch); await h.asElement().click(); await sleep(90); }
  await sleep(800); t = await T();
  ok(t.phase === 'done' && t.pearls === p0 + 10, 'tiles answer accepted (+10)');
  await page.click('#quitBtn'); await sleep(300);
  ok(await visible('#scr-home'), 'Home button leaves the round');

  console.log('8. Word list');
  await page.click('.mode-btn[data-mode="list"]'); await sleep(400);
  ok(await count('#wordList .word-row') === 50, '50 words in the 4th grade list');
  ok(await page.$eval('#chipCrossed', el => el.hidden), 'crossed-off chip hidden for 4th grade');
  ok(await count('#wordList .word-row[data-w="December"]') === 1, 'December listed with its capital');
  await page.click('#wordList .word-row[data-w="December"]'); await sleep(250);
  ok((await text('#wordDetail')).indexOf('twelfth') >= 0, 'word detail shows the meaning');
  await page.click('#wordsHome'); await sleep(300);

  console.log('9. December accepts lowercase');
  await page.evaluate(() => { const w = __spelling.WORDS4.find(x => x.w === 'December'); __spelling.startRound('spell', [w]); });
  await sleep(500); await typeAnswer('december');
  t = await T(); ok(t.phase === 'done', 'lowercase december accepted');
  await page.evaluate(() => document.getElementById('quitBtn').click()); await sleep(300);
  await page.evaluate(() => { const w = __spelling.WORDS4.find(x => x.w === 'kelp'); __spelling.startRound('spell', [w]); });
  await sleep(500); await typeAnswer('KeLP');
  t = await T(); ok(t.phase === 'done', 'mixed-case KeLP accepted');
  ok(await page.$eval('#spellInput', el => getComputedStyle(el).textTransform === 'none'), 'spelling box keeps what she types');
  await page.evaluate(() => document.getElementById('quitBtn').click()); await sleep(300);
  await page.evaluate(() => { const w = __spelling.WORDS4.find(x => x.w === 'December'); __spelling.startRound('spell', [w]); });
  await sleep(500); await typeAnswer('DECEMBAR');
  ok((await T()).phase === 'lockin' && await count('#resultBox .tile.ok') === 7, 'diff ignores case: 7 letters match in DECEMBAR');
  await page.evaluate(() => document.getElementById('quitBtn').click()); await sleep(300);

  console.log('10. Switching players and persistence');
  const charliePearls = (await T()).pearls;
  await page.click('#switchBtn'); await sleep(350);
  ok(await visible('#scr-profiles'), 'switch shows the player screen');
  ok((await text('.profile-card[data-id="charlie"] .pc-sub')).indexOf('level ' + t.level) >= 0, 'Charlie card shows her level');
  await page.click('.profile-card[data-id="riley"]'); await sleep(500);
  ok(await world() === 'lagoon' && await text('#playerName') === 'Riley', 'Riley lands in the lagoon');
  ok((await T()).pearls === 0, 'Riley starts at 0 pearls');
  ok(await text('#axoNameHome') === 'Axolotl', 'Riley default character');
  ok(await count('.char-chip') === 6 && await count('.char-chip[data-char="penguin"]') === 1, 'six lagoon characters');
  await page.click('.mode-btn[data-mode="list"]'); await sleep(350);
  ok(await count('#wordList .word-row') === 50 && !(await page.$eval('#chipCrossed', el => el.hidden)), '3rd grade list with the crossed-off chip');
  await page.click('#chipCrossed'); await sleep(250);
  ok(await count('#wordList .word-row') === 17, '17 crossed-off words');
  await page.click('#wordsHome'); await sleep(250);
  await page.click('#gradeSeg .seg-btn[data-g="4"]'); await away();
  ok(await world() === 'candy' && (await T()).grade === '4', 'Riley can switch to 4th grade');
  await page.click('#gradeSeg .seg-btn[data-g="3"]'); await away();
  await page.click('#switchBtn'); await sleep(300); await page.click('.profile-card[data-id="charlie"]'); await sleep(500);
  ok((await T()).pearls === charliePearls && await world() === 'candy', 'Charlie progress intact after switching');
  await page.reload({ waitUntil: 'load' }); await sleep(700);
  ok(await visible('#scr-profiles'), 'reload shows the player screen');
  await page.click('.profile-card[data-id="charlie"]'); await sleep(500);
  ok((await T()).pearls === charliePearls, 'Charlie progress survives a reload');
  ok(await text('#axoNameHome') === 'Cupcake', 'character choice survives a reload');

  console.log('10b. Saves are safe before a player is picked');
  const keepPearls = (await T()).pearls;
  await page.evaluate(() => { __spelling.G.cur = null; }); await page.reload({ waitUntil: 'load' }); await sleep(600);
  await page.click('#soundBtn'); await sleep(150); await page.click('#soundBtn'); await sleep(150);
  await page.click('.profile-card[data-id="charlie"]'); await sleep(500);
  ok((await T()).pearls === keepPearls, 'sound button on the player screen does not wipe the last save');
  await page.click('.mode-btn[data-mode="list"]'); await sleep(300); await page.click('#wordList .word-row'); await sleep(200);
  await page.click('#wordsHome'); await sleep(200); await page.click('#switchBtn'); await sleep(300);
  await page.click('.profile-card[data-id="riley"]'); await sleep(400); await page.click('.mode-btn[data-mode="list"]'); await sleep(300);
  ok((await text('#wordDetail')).indexOf('Tap a word') >= 0 && await count('#wordList .word-row.on') === 0, 'word detail does not carry over to the other player');
  await page.click('#wordsHome'); await sleep(200); await page.click('#switchBtn'); await sleep(300); await page.click('.profile-card[data-id="charlie"]'); await sleep(400);
  await page.evaluate(() => { const w = __spelling.WORDS4.find(x => x.w === 'kelp'); __spelling.startRound('tiles', [w]); }); await sleep(400);
  await page.evaluate(() => { const L = __spelling.G.tileLetters, want = 'kelp'.split(''), used = []; want.forEach(ch => { const i = L.findIndex((c, j) => c === ch && used.indexOf(j) < 0); used.push(i); document.querySelector('#tiles .tile.pick[data-i="' + i + '"]').click(); }); document.querySelector('#slots .tile.slot[data-i="3"]').click(); });
  await sleep(600);
  ok((await T()).phase === 'answer', 'removing a tile right after filling the row cancels the auto-check');
  await page.evaluate(() => document.getElementById('quitBtn').click()); await sleep(300);

  console.log('10c. Two tabs never overwrite each other');
  const stored = () => page.evaluate(() => JSON.parse(localStorage.getItem('spelling-worlds-charlie')).worlds.candy.pearls);
  const q0 = await stored();
  const page2 = await browser.newPage(); await cloud.attach(page2); await page2.setViewport({ width: 1200, height: 900 });
  await page2.goto(URL, { waitUntil: 'load' }); await sleep(500);
  await page2.$eval('.profile-card[data-id="charlie"]', el => el.click()); await sleep(400);
  const answerIn = (pg, word) => pg.evaluate((word) => { const w = __spelling.WORDS4.find(x => x.w === word); __spelling.startRound('spell', [w]); document.getElementById('spellInput').value = w.w; document.getElementById('checkBtn').click(); document.getElementById('quitBtn').click(); }, word);
  await answerIn(page, 'kelp'); await sleep(300);
  await page2.evaluate(() => { document.dispatchEvent(new Event('visibilitychange')); });
  await answerIn(page2, 'lunar'); await sleep(300);
  ok(await stored() === q0 + 20, 'answers from both tabs count (' + q0 + ' -> ' + (await stored()) + ')');
  await page.evaluate(() => { __spelling.S.worlds.candy.pearls -= 5000; });
  await answerIn(page2, 'elite'); await sleep(300);
  ok(await stored() === q0 + 30, 'a tab holding old numbers cannot lower the save');
  await page2.$eval('#gradeSeg .seg-btn[data-g="3"]', el => el.click()); await sleep(200); await page2.$eval('#gradeSeg .seg-btn[data-g="4"]', el => el.click()); await sleep(200);
  ok(await stored() === q0 + 30, 'switching grades in another tab keeps the progress');
  await page2.close();
  await page.reload({ waitUntil: 'load' }); await sleep(500); await page.click('.profile-card[data-id="charlie"]'); await sleep(400);

  console.log('10d. Vera and the rainforest');
  await page.click('#switchBtn'); await sleep(300);
  await page.hover('.profile-card[data-id="vera"]'); await sleep(250);
  ok(await world() === 'canopy' && await text('#brand') === 'Spelling Canopy', 'hovering Vera previews the rainforest');
  await away();
  await page.click('.profile-card[data-id="vera"]'); await sleep(500);
  ok(await world() === 'canopy' && await text('#playerName') === 'Vera', 'Vera lands in the rainforest');
  ok(await text('#axoNameHome') === 'Sloth' && await attr('.char-chip.on', 'data-char') === 'sloth', 'Vera starts as a sloth');
  ok(await count('.char-chip') === 6, 'six rainforest characters');
  ok(await attr('.seg-btn.on', 'data-g') === '4', 'Vera on the 4th grade list');
  await page.hover('#gradeSeg .seg-btn[data-g="3"]'); await sleep(250);
  ok(await world() === 'canopy', 'grade hover keeps the rainforest for Vera');
  await page.click('#gradeSeg .seg-btn[data-g="3"]'); await away();
  ok(await world() === 'canopy' && await text('#gradeLabel') === '3rd grade', '3rd grade words, still the rainforest');
  await page.click('#gradeSeg .seg-btn[data-g="4"]'); await away();
  for (const c of ['toucan', 'monkey', 'treefrog', 'jaguar', 'gotter', 'sloth']) { await page.click('.char-chip[data-char="' + c + '"]'); await sleep(120); }
  ok(await text('#axoNameHome') === 'Sloth' && await count('#axoHome svg ellipse') > 5, 'every rainforest character draws');
  await page.evaluate(() => { const w = __spelling.WORDS3.find(x => x.w === 'sloth'); __spelling.startRound('spell', [w]); }); await sleep(500);
  ok(!/sloth/i.test(await page.evaluate(() => document.getElementById('app').innerText)), 'the word sloth is not shown while it is being tested');
  await typeAnswer('sloth'); t = await T();
  ok(t.phase === 'done' && t.pearls === 10, 'Vera earns 10 leaves');
  ok(!/sloth/i.test(await page.evaluate(() => document.getElementById('app').innerText)), 'praise never names the word');
  await page.evaluate(() => document.getElementById('quitBtn').click()); await sleep(300);
  ok((await T()).pearls === 10 && (await page.evaluate(() => JSON.parse(localStorage.getItem('spelling-worlds-vera')).worlds.canopy.pearls)) === 10, 'Vera save is separate');
  await page.evaluate(() => { __spelling.S.worlds.canopy.pearls = 1400; __spelling.save(); }); await page.reload({ waitUntil: 'load' }); await sleep(500);
  await page.click('.profile-card[data-id="vera"]'); await sleep(600);
  ok(await text('#lbLevel') === 'Level 10' && await count('#scene [data-lv="10"].on') > 0 && await count('#axoHome .acc.on') >= 5, 'rainforest level 10 shows its scenery and outfit');
  await page.screenshot({ path: 'vera-10.png' });
  await page.click('#switchBtn'); await sleep(300); await page.click('.profile-card[data-id="charlie"]'); await sleep(500);

  console.log('10e. Cora and the ocean');
  await page.click('#switchBtn'); await sleep(300);
  await page.hover('.profile-card[data-id="cora"]'); await sleep(250);
  ok(await world() === 'ocean' && await text('#brand') === 'Spelling Ocean', 'hovering Cora previews the ocean');
  await away();
  await page.click('.profile-card[data-id="cora"]'); await sleep(500);
  ok(await world() === 'ocean' && await text('#playerName') === 'Cora', 'Cora lands in the ocean');
  ok(await text('#axoNameHome') === 'Jellyfish' && await attr('.char-chip.on', 'data-char') === 'jellyfish', 'Cora starts as a jellyfish');
  ok(await count('.char-chip') === 6, 'six ocean characters');
  ok(await attr('.seg-btn.on', 'data-g') === '4', 'Cora on the 4th grade list');
  await page.hover('#gradeSeg .seg-btn[data-g="3"]'); await sleep(250);
  ok(await world() === 'ocean', 'grade hover keeps the ocean for Cora');
  await page.click('#gradeSeg .seg-btn[data-g="3"]'); await away();
  ok(await world() === 'ocean' && await text('#gradeLabel') === '3rd grade', '3rd grade words, still the ocean');
  await page.click('#gradeSeg .seg-btn[data-g="4"]'); await away();
  for (const c of ['octopus', 'seahorse', 'clownfish', 'narwhal', 'pufferfish', 'jellyfish']) { await page.click('.char-chip[data-char="' + c + '"]'); await sleep(120); }
  ok(await text('#axoNameHome') === 'Jellyfish' && await count('#axoHome svg path') > 5, 'every ocean character draws');
  await page.evaluate(() => { const w = __spelling.WORDS4.find(x => x.w === 'lunar'); __spelling.startRound('spell', [w]); }); await sleep(500);
  await typeAnswer('lunar'); t = await T();
  ok(t.phase === 'done' && t.pearls === 10, 'Cora earns 10 bubbles');
  await page.evaluate(() => document.getElementById('quitBtn').click()); await sleep(300);
  ok((await T()).pearls === 10 && (await page.evaluate(() => JSON.parse(localStorage.getItem('spelling-worlds-cora')).worlds.ocean.pearls)) === 10, 'Cora save is separate');
  await page.evaluate(() => { __spelling.S.worlds.ocean.pearls = 1400; __spelling.save(); }); await page.reload({ waitUntil: 'load' }); await sleep(500);
  await page.click('.profile-card[data-id="cora"]'); await sleep(600);
  ok(await text('#lbLevel') === 'Level 10' && await count('#scene [data-lv="10"].on') > 0 && await count('#axoHome .acc.on') >= 5, 'ocean level 10 shows its scenery and outfit');
  await page.screenshot({ path: 'cora-10.png' });
  await page.evaluate(() => document.getElementById('resetBtn').click()); await sleep(200); await page.evaluate(() => document.getElementById('resetYes').click()); await sleep(400);
  ok(await world() === 'ocean' && await count('.char-chip[data-char="jellyfish"]') === 1 && await text('#lbLevel') === 'Level 0', 'reset keeps Cora in the ocean');
  await page.click('#switchBtn'); await sleep(300); await page.click('.profile-card[data-id="charlie"]'); await sleep(500);

  console.log('11. Sound toggle and reset');
  await page.click('#soundBtn'); await sleep(100);
  ok(await page.$eval('#soundBtn', el => el.classList.contains('off')), 'sound off');
  await page.click('#soundBtn'); await sleep(100);
  await page.click('#resetBtn'); await sleep(150); ok(await visible('#resetConfirm'), 'reset asks first');
  await page.click('#resetNo'); await sleep(150); ok(!(await visible('#resetConfirm')), 'Keep them cancels');
  await page.click('#resetBtn'); await sleep(100); await page.click('#resetYes'); await sleep(400);
  ok((await T()).pearls === 0 && await text('#lbLevel') === 'Level 0', 'reset clears progress');
  ok(await text('#axoNameHome') === 'Cupcake' && await world() === 'candy', 'reset keeps character and grade');

  console.log('12. Phone layout');
  await page.setViewport({ width: 390, height: 844, isMobile: true, hasTouch: true }); await sleep(500);
  const fits = () => page.evaluate(() => { const m = document.getElementById('main'); return document.documentElement.scrollWidth <= window.innerWidth + 1 && m.scrollWidth <= m.clientWidth + 1; });
  ok(await fits(), 'home fits at 390px wide');
  await tap('.mode-btn[data-mode="spell"]'); await sleep(600);
  ok(await fits(), 'play screen fits');
  ok(await page.$eval('#checkBtn', el => el.getBoundingClientRect().height >= 44), 'Check button is tap-sized');
  ok(await page.$eval('#spellInput', el => el.getBoundingClientRect().width > 250), 'spelling box is wide');
  await tap('#quitBtn'); await sleep(250);
  await tap('.mode-btn[data-mode="list"]'); await sleep(350);
  ok(await fits(), 'word list fits');
  await tap('#wordsHome'); await sleep(250);
  await tap('#switchBtn'); await sleep(300);
  ok(await fits(), 'player screen fits');
  console.log('12b. Keyboard-height view');
  await tap('.profile-card[data-id="charlie"]'); await sleep(500);
  await page.setViewport({ width: 390, height: 430, isMobile: true, hasTouch: true }); await sleep(500);
  await tap('.mode-btn[data-mode="spell"]'); await sleep(800);
  const within = (sel) => page.$eval(sel, el => { const r = el.getBoundingClientRect(); return r.height > 0 && r.top >= -1 && r.bottom <= window.innerHeight + 1; });
  ok(await page.evaluate(() => document.getElementById('app').getBoundingClientRect().height <= window.innerHeight + 1), 'app fits the visible height');
  ok(await within('#spellInput'), 'spelling box visible in a keyboard-sized view');
  ok(await within('#checkBtn'), 'Check button visible in a keyboard-sized view');
  ok(await page.$eval('.levelbar', el => el.offsetParent === null), 'level bar hidden during play on phones');
  await typeAnswer('zzq'); await sleep(700);
  ok(await within('#resultBox'), 'feedback visible after a miss in a keyboard-sized view');
  ok(await within('#spellInput'), 'spelling box still reachable for the lock-in retype');
  t = await T(); await typeAnswer(t.word); await sleep(600);
  ok((await T()).phase === 'done' && await page.$eval('#spellInput', el => el.readOnly && document.activeElement === el), 'input stays focused (keyboard stays open) after an answer');
  await tap('#quitBtn'); await sleep(300);

  console.log('12c. Every word in both lists, both modes');
  await page.setViewport({ width: 1200, height: 900 }); await sleep(300);
  const sweep = await page.evaluate(() => {
    const H = __spelling, bad = [], G = () => H.G, click = () => document.getElementById('checkBtn').click();
    const order = (word) => { const used = [], L = G().tileLetters; return word.toLowerCase().split('').map(ch => { for (let i = 0; i < L.length; i++) { if (L[i] === ch && used.indexOf(i) < 0) { used.push(i); return i; } } return -1; }); };
    for (const w of H.WORDS3.concat(H.WORDS4)) {
      H.startRound('spell', [w]); document.getElementById('spellInput').value = w.w.toUpperCase(); click();
      if (G().phase !== 'done') bad.push('spell upper: ' + w.w);
      H.startRound('spell', [w]); document.getElementById('spellInput').value = ' ' + w.w.toLowerCase() + ' '; click();
      if (G().phase !== 'done') bad.push('spell lower: ' + w.w);
      H.startRound('tiles', [w]);
      if (G().tileLetters.join('') === w.w.toLowerCase() && w.w.length > 2) bad.push('tiles not scrambled: ' + w.w);
      if (G().tileLetters.some(c => c !== c.toLowerCase())) bad.push('tile has a capital: ' + w.w);
      let o = order(w.w); if (o.indexOf(-1) >= 0) { bad.push('tiles missing letters: ' + w.w); continue; }
      G().tileSel = o; click(); if (G().phase !== 'done') bad.push('tiles correct: ' + w.w);
      H.startRound('tiles', [w]); o = order(w.w); const rev = o.slice().reverse();
      if (rev.map(i => G().tileLetters[i]).join('') !== w.w.toLowerCase()) { G().tileSel = rev; click(); if (G().phase !== 'lockin') bad.push('tiles wrong -> lockin: ' + w.w); o = order(w.w); G().tileSel = o; click(); if (G().phase !== 'done') bad.push('tiles lock-in retype: ' + w.w); }
      const re = new RegExp(w.w, 'ig'); if (!re.test(w.s)) bad.push('sentence lacks the word: ' + w.w);
      if (w.w !== w.w.toLowerCase() && w.w !== 'December') bad.push('unexpected capital in word: ' + w.w);
      const pre = w.w.toLowerCase().slice(0, Math.min(5, w.w.length));
      if (w.d.toLowerCase().indexOf(pre) >= 0) bad.push('meaning gives it away: ' + w.w);
      if (w.s.replace(new RegExp(w.w, 'ig'), '____').toLowerCase().indexOf(pre) >= 0) bad.push('blanked sentence gives it away: ' + w.w);
    }
    return bad;
  });
  ok(sweep.length === 0, 'all 100 words pass upper/lower typing, tiles, and tile lock-in' + (sweep.length ? ': ' + sweep.slice(0, 8).join(' | ') : ''));
  await page.evaluate(() => { const b = document.getElementById('quitBtn'); b.click(); }); await sleep(400);
  await page.evaluate(() => { const w = __spelling.WORDS4.find(x => x.w === 'December'); __spelling.startRound('tiles', [w]); }); await sleep(400);
  await page.click('#hintBtn'); await sleep(200);
  ok(await count('#tiles .tile.pick.glow') === 1 && (await text('#tiles .tile.pick.glow')) === 'd', 'December hint glows the lowercase d tile');
  await page.evaluate(() => document.getElementById('quitBtn').click()); await sleep(300);
  console.log('12d. Charlie restore');
  await page.setViewport({ width: 1200, height: 900 });
  delete cloud.store.charlie; delete cloud.store.riley;
  await page.evaluate(() => { ['spelling-worlds-charlie', 'spelling-worlds-sync-charlie', 'spelling-worlds-sync-riley'].forEach(k => localStorage.removeItem(k)); }); await page.reload({ waitUntil: 'load' }); await sleep(600);
  ok((await text('.profile-card[data-id="charlie"] .pc-sub')).indexOf('level 10') >= 0, 'Charlie card shows level 10 after the restore');
  await page.click('.profile-card[data-id="charlie"]'); await sleep(500);
  ok((await T()).pearls >= 1458 && await text('#lbLevel') === 'Level 10' && await world() === 'candy', 'Charlie is back at level 10 in the candy world');
  ok(await page.evaluate(() => JSON.parse(localStorage.getItem('spelling-worlds-charlie')).restoredId === 'r20260927'), 'restore is saved and applies only once');

  await page.evaluate(() => { localStorage.setItem('spelling-worlds-riley', JSON.stringify({ restoredId: 'r20260927b', worlds: { lagoon: { pearls: 360, wearLevel: null }, candy: { pearls: 0, wearLevel: null } } })); }); await page.reload({ waitUntil: 'load' }); await sleep(500);
  ok((await text('.profile-card[data-id="riley"] .pc-sub')).indexOf('3rd grade, level 3') >= 0, 'the level 5 raise is undone: Riley back at level 3, keeping 10 earned since');
  await page.click('.profile-card[data-id="riley"]'); await sleep(400); ok((await T()).pearls === 171, 'Riley has 171 pearls');

  console.log('12e. Levels 11-20 need mastered words');
  const pickPlayer = async (id) => { await page.reload({ waitUntil: 'load' }); await sleep(500); await page.click('.profile-card[data-id="' + id + '"]'); await sleep(500); };
  const master = (list, n) => page.evaluate((list, n) => { const L = __spelling[list]; for (let i = 0; i < n; i++) __spelling.S.words[L[i].w] = { streak: 3, right: 3, wrong: 0, seen: 3, mastered: true }; __spelling.save(); }, list, n);
  await page.click('#switchBtn'); await sleep(300); await page.click('.profile-card[data-id="riley"]'); await sleep(400);
  await page.evaluate(() => { __spelling.S.words = {}; __spelling.S.epoch = (__spelling.S.epoch || 0) + 1; __spelling.S.worlds.lagoon.pearls = 5000; __spelling.save(); }); await pickPlayer('riley');
  ok(await text('#lbLevel') === 'Level 10' && (await text('#lbNext')).indexOf('10 words mastered') >= 0, 'plenty of pearls but no mastered words stops at level 10');
  ok((await text('.level-card.mystery .lc-sub')).indexOf('10 mastered') >= 0, 'surprise card names the mastery goal');
  await master('WORDS3', 25); await pickPlayer('riley');
  ok(await text('#lbLevel') === 'Level 14' && await count('#scene [data-lv="14"].on') > 0 && await count('#axoHome .acc.on[data-lv="14"]') === 1, '25 mastered words reach level 14 with its scenery and extra');
  ok(await count('#axoHome .acc.on[data-lv="12"] ellipse') > 3, 'tiny buddy draws');
  await master('WORDS3', 50); await pickPlayer('riley');
  ok(await text('#lbLevel') === 'Level 20' && await text('#lbNext') === 'Top level reached!' && await count('#axoHome .acc.on[data-lv="20"]') === 1 && await count('#scene [data-lv="20"].on') > 0, 'all 50 mastered reaches level 20 with the trophy');
  ok(await text('#masteredCount') === '50', 'home shows 50 of 50 mastered');
  await page.click('#switchBtn'); await sleep(300); await page.click('.profile-card[data-id="vera"]'); await sleep(400);
  await page.evaluate(() => { __spelling.S.words = {}; __spelling.S.epoch = (__spelling.S.epoch || 0) + 1; __spelling.S.worlds.canopy.pearls = 5000; __spelling.save(); }); await master('WORDS4', 25); await pickPlayer('vera');
  ok(await text('#lbLevel') === 'Level 14', 'Vera at level 14');
  await page.click('#gradeSeg .seg-btn[data-g="3"]'); await away();
  ok(await text('#lbLevel') === 'Level 14', 'switching grades never lowers the level');
  await page.click('#gradeSeg .seg-btn[data-g="4"]'); await away();
  const answer = (word, hint) => page.evaluate((word, hint) => { const w = __spelling.WORDS4.find(x => x.w === word); __spelling.startRound('spell', [w]); if (hint) document.getElementById('hintBtn').click(); document.getElementById('spellInput').value = w.w; document.getElementById('checkBtn').click(); document.getElementById('quitBtn').click(); return JSON.stringify(__spelling.S.words[w.w]); }, word, hint);
  const hinted = JSON.parse(await answer('opposite', true));
  ok(hinted.streak === 0 && !hinted.mastered, 'a hinted answer does not count toward mastery');
  await answer('opposite'); await answer('opposite'); const third = JSON.parse(await answer('opposite'));
  ok(third.mastered === true, 'three clean answers in a row master a word');
  await page.evaluate(() => { const w = __spelling.WORDS4.find(x => x.w === 'opposite'); __spelling.startRound('spell', [w]); document.getElementById('spellInput').value = 'opposit'; document.getElementById('checkBtn').click(); document.getElementById('quitBtn').click(); });
  ok(await page.evaluate(() => __spelling.S.words.opposite.mastered === true && __spelling.S.words.opposite.streak === 0), 'a later miss keeps the word mastered');
  await page.evaluate(() => { __spelling.S.words = {}; __spelling.S.epoch = (__spelling.S.epoch || 0) + 1; __spelling.S.worlds.canopy.pearls = 1600; __spelling.save(); }); await master('WORDS4', 9); await pickPlayer('vera');
  ok(await text('#lbLevel') === 'Level 10', 'Vera at level 10 with 9 mastered');
  for (let i = 0; i < 3; i++) await answer('lunar');
  await sleep(1800);
  ok(await text('#lbLevel') === 'Level 11', 'mastering the 10th word levels up to 11');
  await page.screenshot({ path: 'lv11.png' });

  console.log('12f. Online saves');
  const waitSync = async (pg) => { for (let i = 0; i < 80; i++) { if (await pg.evaluate(() => __spelling.cloud.idle())) return true; await sleep(100); } return false; };
  const onlinePearls = (id, w) => { const x = cloud.store[id]; return x && x.state.worlds[w] ? x.state.worlds[w].pearls : 0; };
  const pearlsIn = (pg, w) => pg.evaluate(w => __spelling.S.worlds[w].pearls, w);
  await page.evaluate(() => __spelling.save()); await sleep(1000);
  ok(await waitSync(page), 'uploads finish');
  ok(onlinePearls('vera', 'canopy') === await pearlsIn(page, 'canopy'), 'the online copy of Vera matches this device (' + onlinePearls('vera', 'canopy') + ')');
  ok(['charlie', 'riley', 'vera', 'cora'].every(id => cloud.store[id]), 'every kid played here has an online save');
  const dev2ctx = await browser.createBrowserContext(); const dev2 = await dev2ctx.newPage(); await cloud.attach(dev2);
  dev2.on('pageerror', e => errors.push('dev2 pageerror: ' + e.message));
  await dev2.setViewport({ width: 1200, height: 900 }); await dev2.goto(URL, { waitUntil: 'load' }); await sleep(600); await waitSync(dev2);
  ok(await dev2.$eval('.profile-card[data-id="vera"] .pc-sub', e => e.textContent) === '4th grade, level 11', 'a new device shows Vera at her online level 11');
  await dev2.evaluate(() => __spelling.selectProfile('vera')); await sleep(400); await waitSync(dev2);
  ok(await pearlsIn(dev2, 'canopy') === onlinePearls('vera', 'canopy'), 'a new device plays on from her online progress');
  ok(await dev2.$eval('#syncHome', e => !e.hidden && e.textContent === 'Saved online'), 'home says Saved online');
  await page.evaluate(() => __spelling.selectProfile('cora')); await dev2.evaluate(() => __spelling.selectProfile('cora')); await sleep(300); await waitSync(page); await waitSync(dev2);
  const c0 = onlinePearls('cora', 'ocean');
  ok(await pearlsIn(page, 'ocean') === c0 && await pearlsIn(dev2, 'ocean') === c0, 'both devices start Cora at ' + c0);
  cloud.ctl.down = true;
  await page.evaluate(() => { __spelling.S.worlds.ocean.pearls += 10; __spelling.save(); });
  await dev2.evaluate(() => { __spelling.S.worlds.ocean.pearls += 25; __spelling.save(); });
  await sleep(1300);
  ok(await page.$eval('#syncHome', e => !e.hidden && /Not connected/.test(e.textContent)), 'offline shows a not-connected note');
  ok(onlinePearls('cora', 'ocean') === c0, 'nothing reaches the service while offline');
  cloud.ctl.down = false;
  for (const pg of [page, dev2, page]) { await pg.evaluate(() => __spelling.cloud.syncAll()); await sleep(150); await waitSync(pg); }
  ok(onlinePearls('cora', 'ocean') === c0 + 35, 'offline rewards from both devices add up online (' + c0 + ' -> ' + onlinePearls('cora', 'ocean') + ')');
  ok(await pearlsIn(page, 'ocean') === c0 + 35 && await pearlsIn(dev2, 'ocean') === c0 + 35, 'both devices show the combined total');
  ok(await page.$eval('#syncHome', e => e.textContent) === 'Saved online', 'the note returns to Saved online');
  cloud.ctl.dropNextReply = true;
  await page.evaluate(() => { __spelling.S.worlds.ocean.pearls += 7; __spelling.save(); }); await sleep(1300);
  await page.evaluate(() => { __spelling.S.worlds.ocean.pearls += 3; __spelling.save(); }); await sleep(1300);
  await page.evaluate(() => __spelling.cloud.syncAll()); await sleep(150); await waitSync(page);
  ok(onlinePearls('cora', 'ocean') === c0 + 45 && await pearlsIn(page, 'ocean') === c0 + 45, 'a save whose reply was lost is not counted twice (' + onlinePearls('cora', 'ocean') + ')');
  await dev2.evaluate(() => __spelling.cloud.syncAll()); await sleep(150); await waitSync(dev2);
  ok(await pearlsIn(dev2, 'ocean') === c0 + 45, 'the other device catches up');
  const posts0 = cloud.stats.posts;
  for (const pg of [page, dev2, page, dev2]) { await pg.evaluate(() => __spelling.cloud.syncAll()); await sleep(150); await waitSync(pg); }
  ok(cloud.stats.posts === posts0, 'syncing again sends nothing new (' + (cloud.stats.posts - posts0) + ' extra saves)');
  await page.evaluate(() => { document.getElementById('resetYes').click(); }); await sleep(1100); await waitSync(page);
  await dev2.evaluate(() => __spelling.cloud.syncAll()); await sleep(150); await waitSync(dev2);
  ok(onlinePearls('cora', 'ocean') === 0 && await pearlsIn(dev2, 'ocean') === 0, 'a reset on one device reaches the other');
  await dev2.evaluate(() => { __spelling.S.worlds.ocean.pearls += 10; __spelling.save(); }); await sleep(1300); await waitSync(dev2);
  await page.evaluate(() => __spelling.cloud.syncAll()); await sleep(150); await waitSync(page);
  ok(onlinePearls('cora', 'ocean') === 10 && await pearlsIn(page, 'ocean') === 10, 'play after a reset starts from zero everywhere');
  ok(await dev2.evaluate(() => __spelling.DEV) !== await page.evaluate(() => __spelling.DEV), 'each device has its own id');
  await dev2ctx.close();
  ok(cloud.stats.realHits === 0, 'tests never reached the real save service');

  console.log('13. Errors');
  ok(errors.length === 0, 'no page errors' + (errors.length ? ': ' + errors.slice(0, 3).join(' | ') : ''));
  await browser.close();
  console.log('\n' + passes + ' passed, ' + fails + ' failed');
  process.exit(fails ? 1 : 0);
})().catch(e => { console.error('TEST CRASH', e); process.exit(2); });
