CREATE TABLE IF NOT EXISTS saves (player TEXT PRIMARY KEY, rev INTEGER NOT NULL, state TEXT NOT NULL, updated INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS history (id INTEGER PRIMARY KEY AUTOINCREMENT, player TEXT NOT NULL, rev INTEGER NOT NULL, state TEXT NOT NULL, at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS history_player ON history (player, id);
